### ISSUE TITLE
动态线程池监控,展示不全面

### ISSUE THREAD

**Issue by towardsvast** [opengoofy/hippo4j#1004]
1. 使用自带的ui监控界面,线程池当中是一直有任务在运行,队列也有积压.但是**活跃线程**和**队列容量**展示为毛刺.图片如下:
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/112958315/203076905-9ecac9d3-e62f-45ad-80a6-0f11450c7120.png">

2. 使用prometheus+grafana监控界面
按照文档步骤以及大佬提供的思路操作,可以展示动态线程池相关参数,但是依旧缺乏**活跃线程**和**队列容量**,展示如下:
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/112958315/203077589-bed9a4ab-ce24-44b5-a895-f9ebb0fcd56c.png">

3. 通过告警,可以发现线程池当中是有**活跃线程**和**队列容量**,展示如下:
![image](https://user-images.githubusercontent.com/112958315/203078147-2bfd62ed-7a05-4332-ae79-612107ad89c8.png)

**Comment by magestacks** [comment]
线程池运行指标采集默认 5s 一次，可能在采集的时候活跃线程数已经下去了。

**Comment by magestacks** [comment]
你可以尝试把采集周期从 5s 切换成 1s 试一下。

**Comment by magestacks** [comment]
Issue 长时间没有反馈，关闭。
