### ISSUE TITLE
关于CallerRunsPolicy拒绝策略的一些使用问题

### ISSUE THREAD

**Issue by paiky** [opengoofy/hippo4j#1017]
## BUG 报告
很奇怪，在定义CallerRunsPolicy拒绝策略时，第一次能完整的执行完所有任务，之后便不能完整执行，而是抛出异常拒绝。定义的参数：core-pool-size: 5  maximum-pool-size: 8  queue-capacity: 2
在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/docs/user_docs/other/issue)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?
hippo4j config
### 你使用了哪个版本？
<version>1.4.3-upgrade</version>
### 预期行为
使用官方ThreadPoolService定义CallerRunsPolicy策略做对比，便没有这个问题出现，多次模拟请求执行任务，都能完整执行完
### 实际行为
只有第一次的请求能执行完所有任务，之后便抛出异常 rejected from cn.hippo4j.core.executor.DynamicThreadPoolExecutor@49469ffa[Running, pool size = 8, active threads = 5, queued tasks = 0, completed tasks = 19]

**Comment by magestacks** [comment]
可以贴一下你的执行代码，以及复现流程。

值得说明的是，Hippo4j 并没有对 CallerRunsPolicy 做任何逻辑外功能修改，直接取自 `new ThreadPoolExecutor.CallerRunsPolicy()`

**Comment by paiky** [comment]
您好，我貌似看出问题了，yml还是配的 rejected-handler: 'AbortPolicy' ，导致Bean设置的.rejected(new ThreadPoolExecutor.CallerRunsPolicy())不生效，yml改了之后现在能生效了

**Comment by magestacks** [comment]
好的。如果有计划公司使用，麻烦 [使用公司](https://hippo4j.cn/users) 上登个记哈。

**Comment by paiky** [comment]
> 好的。如果有计划公司使用，麻烦 [使用公司](https://hippo4j.cn/users) 上登个记哈。

好，目前是个人在学习，赞👍
