### ISSUE TITLE
hippo4j-spring-boot-starter-adapter-rabbitmq-example 模块，配置文件缺少spring.application.name 

### ISSUE THREAD

**Issue by baymax55** [opengoofy/hippo4j#1019]
hippo4j-spring-boot-starter-adapter-rabbitmq-example 模块，配置文件缺少spring.application.name 导致服务无法正常启动，我看其他example模块默认配置了spring.application.name

分支：develop

![1669548898976](https://user-images.githubusercontent.com/35788491/204133282-5bb1b910-bfb5-4b9f-861f-a314427abef3.jpg)

**Comment by magestacks** [comment]
这应该开发者疏忽了，有兴趣提个 PR 解决下么
