### ISSUE TITLE
线程池配置钉钉告警，初始化报错

### ISSUE THREAD

**Issue by chufa** [opengoofy/hippo4j#1022]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/docs/user_docs/other/issue)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?
spring-cloude 2.2.9.RELEASE 版本使用hippo4j config 1.4.3-upgrade

### 预期行为
钉钉告警配置如下：
notify-platforms:
        - platform: 'DING'
          token: xxxx
          secret-key: xxxx

### 实际行为
告警生效，但修改线程池参数时，告警配置会报错

### 原因分析（如果可以）
secret-key 在1.4.3-upgrade版本中标记位废弃，改为secret，但是如果仅仅是标记为废弃，不应该报错

### 问题重现步骤
如上配置，会报错异常

正确配置：
notify-platforms:
        - platform: 'DING'
          token: xxxx
          secret: xxxx

**Comment by pirme** [comment]
先说下你预期的功能，钉钉是否限制了签名访问，还是说关键字访问就可以。

另外发下报错信息。

**Comment by chufa** [comment]
@pirme 我上面意思是既然secret-key 这个字段标记为废弃，不是直接移除，那用户不管是配置secret-key 还是secret应该都能用才对，不应该是配置的废弃字段而初始化报错

**Comment by pirme** [comment]
两个原因：

1. 官网已更新最新的接入方式，而不是用户看到废弃依然使用。我想字段上也标记了使用新字段说明。
2. 如果直接移除不如标记废弃容易理解，切换到新的配置有个过渡期。会在后续大版本迭代中删除过期配置。
