### ISSUE TITLE
告警通知扩展能力

### ISSUE THREAD

**Issue by chufa** [opengoofy/hippo4j#1023]
## 需求建议

请在提交问题之前回答这些问题，谢谢。

### 描述你想要的功能
目前支持的告警能力有：钉钉、微信、lark等，这里是否支持用户额外扩展告警能力，比如开发一个插件集成一下，就可以发送招呼、手机短信、邮箱告警

**Comment by magestacks** [comment]
实现 `cn.hippo4j.message.service.SendMessageHandler` 接口，声明为 Spring Bean 即可。
