### ISSUE TITLE
客户端与 Hippo4j revision 冲突

### ISSUE THREAD

**Issue by HuangDayu** [opengoofy/hippo4j#1024]
## 问题支持

如果我的项目也定义`revision`，而hippo4j-spring-boot-starter也定义了`revision`，并且把revision提交到中央仓库，这将导致不能拉取依赖，因为`revision`定义使用了我的项目的revision值，而不是`1.4.3-upgrade` 。

<https://repo1.maven.org/maven2/cn/hippo4j/hippo4j-spring-boot-starter/1.4.3-upgrade/hippo4j-spring-boot-starter-1.4.3-upgrade.pom>

**Comment by pirme** [comment]
没明白你的问题，你的项目 revision 和 hippo4j 没关系吧

**Comment by HuangDayu** [comment]
![微信图片_20221206144523](https://user-images.githubusercontent.com/23421574/205840703-1a4cbbec-2088-4510-b202-dba8d8db5015.png)

会导致找不到依赖。@pirme

**Comment by pirme** [comment]
有时候 Pom 报红不代表运行有问题，实际运行中会出现问题么

**Comment by HuangDayu** [comment]
编译都不通过，因为找不到依赖。例如我的revision 是1.0，但是hippo4j-spring-boot-starter并没有1.0，所以找不到依赖。 @pirme

**Comment by pirme** [comment]
ok，有时间我试下。现在的解决方案就是，你把标记了 revision 的依赖，在你 pom 里重新依赖下我认为就可以了。如果确实有问题，下个版本修复该问题。

**Comment by HuangDayu** [comment]
好的。

**Comment by baymax55** [comment]
> ![微信图片_20221206144523](https://user-images.githubusercontent.com/23421574/205840703-1a4cbbec-2088-4510-b202-dba8d8db5015.png)
> 
> 会导致找不到依赖。@pirme

这里使用 ${project.version}会更合适点吧

**Comment by pirme** [comment]
@baymax55 是的，你有兴趣提个 PR 修复下么

**Comment by baymax55** [comment]
> @baymax55 是的，你有兴趣提个 PR 修复下么

好的,我来处理下
