### ISSUE TITLE
优化BlockingQueueTypeEnum实现

### ISSUE THREAD

**Issue by lianyiwuming** [opengoofy/hippo4j#1025]
## 需求建议

    BlockingQueueTypeEnum 枚举类定义了队列的类型，同时也对应了队列的创建方式，所以，建议把队列创建的职责，给到每个枚举类型。这也是 effective java 中的经典范例。

### 您的功能请求是否与问题有关？
   无。刚好看到这个项目了，之前也有类似的想法。所以就进来看看。

### 描述你想要的功能
    如建议描述。  另外，单独对外暴露队列创建工厂，把BlockingQueueTypeEnum作为实现隐藏起来，可能更好。
    
对此我刚好最近有时间，我会提一个pr。

**Comment by pirme** [comment]
Welcome
