### ISSUE TITLE
动态刷新线程池参数重复设置，存在无效判断

### ISSUE THREAD

**Issue by NewsDLi** [opengoofy/hippo4j#1030]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/docs/user_docs/other/issue)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?
hippo4j-config-spring-boot-starter

### 你使用了哪个版本？
1.4.1-SNAPSHOT

cn.hippo4j.core.springboot.starter.refresher.event.DynamicThreadPoolRefreshListener#dynamicRefreshPool

 // 这里判断赋值和下面的else没什么区别，是想判断最大线程数与核心线程数做对比吗？
![image](https://user-images.githubusercontent.com/34914455/206644379-7c6451dc-03a8-45ed-84a1-431c5e58843d.png)

**Comment by pirme** [comment]
是问题还是 BUG？

**Comment by NewsDLi** [comment]
是个疑问吧，为什么这么写，没看明白？

**Comment by pirme** [comment]
高版本 JDK 存在线程数判断，可以看下 JDK9 以上的线程池源码

**Comment by NewsDLi** [comment]
看了高版本的源码，拨开云雾见光明那，多谢指教，受教了

**Comment by baymax55** [comment]
> 看了高版本的源码，拨开云雾见光明那，多谢指教，受教了

@NewsDLi  我看了jdk11和jdk1.8,没看出来区别,可以说说你弟理解吗

![image](https://user-images.githubusercontent.com/35788491/206985969-1684e304-d49d-4094-a267-70ef12955957.png)
![image](https://user-images.githubusercontent.com/35788491/206986137-9836ab61-0457-423b-9ff2-beac8fb90b41.png)

**Comment by baymax55** [comment]
> 看了高版本的源码，拨开云雾见光明那，多谢指教，受教了

仅仅是因为这块校验吗: `maximumPoolSize < corePoolSize`

**Comment by baymax55** [comment]
> ## BUG 报告
> 在开始报告错误之前，请确保认真查看了以下步骤：
> 
> * 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
> * 阅读 [常见问题文档](https://hippo4j.cn/docs/user_docs/other/issue)
> 
> 请在提交问题之前回答这些问题，谢谢。
> 
> ### 你使用了哪个项目？hippo4j config 还是 hippo4j server?
> hippo4j-config-spring-boot-starter
> 
> ### 你使用了哪个版本？
> 1.4.1-SNAPSHOT
> 
> cn.hippo4j.core.springboot.starter.refresher.event.DynamicThreadPoolRefreshListener#dynamicRefreshPool
> 
> // 这里判断赋值和下面的else没什么区别，是想判断最大线程数与核心线程数做对比吗？ ![image](https://user-images.githubusercontent.com/34914455/206644379-7c6451dc-03a8-45ed-84a1-431c5e58843d.png)

如果仅仅是考虑到新设置的最大线程数大于原执行器最大线程数问题: 存在新设置的最小核心线程数大于原执行器最大线程数而先执行 `setMaximumPoolSize(xxx)`,后执行`setCorePoolSize(xxx)`,但是在JVM进行编译时,是无法保证是否按此代码执行顺序执行的.因为后者不依赖于前者的执行

**Comment by NewsDLi** [comment]
我没考虑到这块（JVM进行编译时是否按此代码执行顺序执行）
