### ISSUE TITLE
线程池参数默认配置与文档描述不符

### ISSUE THREAD

**Issue by wulangcode** [opengoofy/hippo4j#1040]
## 需求建议
<img width="991" alt="image" src="https://user-images.githubusercontent.com/48200100/208118863-c07f9d02-7996-4cc9-bd7f-b4c115568125.png">

部分配置文件：
```
spring.dynamic.thread-pool.default-executor.keep-alive-time=1200
spring.dynamic.thread-pool.executors[0].core-pool-size=16
spring.dynamic.thread-pool.executors[0].maximum-pool-size=16
spring.dynamic.thread-pool.executors[0].thread-pool-id=wechat
spring.dynamic.thread-pool.executors[0].queue-capacity=1000
```
期望结果是填充`wechat`的`keep-alive-time`参数值为1200。
实际结果：
<img width="664" alt="image" src="https://user-images.githubusercontent.com/48200100/208117624-39e9ad0b-f660-4bc8-ae37-85cc887cad0f.png">
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/48200100/208117802-e03ff355-9114-4666-86d6-50b23009ef73.png">

如果认为这是问题，请指派给我。

**Comment by magestacks** [comment]
我想这是个问题，麻烦帮忙看下，已指派。
