### ISSUE TITLE
自定义线程池的适配问题，比如链路追踪的包裹过的线程池

### ISSUE THREAD

**Issue by lingfengcoder** [opengoofy/hippo4j#1045]
## 需求建议

链路追踪的包裹过的线程池，不能自动管理，建议将适配器开放出来，开发者可自行指定适配器

例子：
https://gitee.com/lingfengx/threadpool-adaptert

直接run即可看到，全局管理器中没有任何可管理的线程池

**Comment by lingfengcoder** [comment]
建议在适配其他包装线程池时，将类名写全，或者直接引用。例如：TransmittableThreadLocalExecutorServiceAdapter 中的 ExecutorServiceTtlWrapper

**Comment by magestacks** [comment]
参考 https://github.com/opengoofy/hippo4j/issues/1055
