### ISSUE TITLE
适配第三方自定义线程池，支持外部SPI方式扩展线程池类型

### ISSUE THREAD

**Issue by lingfengcoder** [opengoofy/hippo4j#1055]
目前hippo4j的线程池支持了大部分的JDK和Spring线程池，但是针对于用户自定义包装过的线程池是不能进行识别的。所以建议，以SPI的方式支持线程池类型的扩展

**Comment by lingfengcoder** [comment]
1.4.3-upgrade 已经添加spi

**Comment by magestacks** [comment]
适配 zipkin ：https://github.com/opengoofy/hippo4j/pull/1047

增加 SPI：https://github.com/opengoofy/hippo4j/pull/1050
