### ISSUE TITLE
关于设置 corePoolSize 和 maxPoolSize 报 IllegalArgumentException

### ISSUE THREAD

**Issue by klook-tech-jayyang** [opengoofy/hippo4j#1063]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues) - 已搜索
- 阅读 [常见问题文档](https://hippo4j.cn/community/faq) - 已阅读

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?

hippo4j config, springboot 2.7.3

### 你使用了哪个版本？

1.4.3-upgrade

### 预期行为

服务正常启动

### 实际行为

执行 DynamicThreadPoolPostProcessor#threadPoolParamReplace 时，setCorePoolSize 报 IllegalArgumentException

### 原因分析（如果可以）

线程池配置类中 ThreadPoolBuilder.builder().build() 时，ThreadPoolBuilder 源码中通过 `calculateCoreNum()` 计算 corePoolSize 的值，之后通过 `this.maxPoolSize = this.corePoolSize + (this.corePoolSize >> 1)` 计算 maxPoolSize 的值，之后在 `DynamicThreadPoolPostProcessor` 中才会通过配置文件中配置的值进行 set。

假如以下场景：`calculateCoreNum()` 计算的值为 20，则 maxPoolSize 值为 30，配置文件中配置 core-pool-size 为 40，则执行到 `DynamicThreadPoolPostProcessor#threadPoolParamReplace` 的 `setCorePoolSize` 时，根据 `ThreadPoolExecutor#setCorePoolSize` 源码，此时 maximumPoolSize(30) < corePoolSize(40)，会报 IllegalArgumentException

### 问题重现步骤

见 原因分析 中

### 修改建议

初始时调大 maxPoolSize 的值，这个值大一点没关系，甚至可以为 `Integer.MAX_VALUE`，因为我们规定用户要配置 core-pool-size 和 maximum-pool-size（不配置会报错），后面也会根据用户配置进行覆盖

**Comment by klook-tech-jayyang** [comment]
如果认为这是 bug，可以指派给我

**Comment by magestacks** [comment]
这是个 BUG。不过对于修改方式，我有着不同看法。

初始时调整 maxPoolSize 为 Integer.MAX_VALUE 最大值并不可取，因为 Server 模式对这个有所依赖。

我认为应该在 `cn.hippo4j.config.springboot.starter.support.DynamicThreadPoolPostProcessor#threadPoolParamReplace` 进行判断，根据核心和最大线程数来设置两者的 set 顺序，你觉得呢？

**Comment by klook-tech-jayyang** [comment]
是的，这样改动也保证影响最小。已提交 pr

**Comment by magestacks** [comment]
已合并，感谢修复
