### ISSUE TITLE
线程池执行超时时间最小值支持 -1

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1069]
涉及到以下两个页面：

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/77398366/222148885-c5744f22-e36a-46c9-a26f-70c7abab7721.png">

<img width="1643" alt="image" src="https://user-images.githubusercontent.com/77398366/222148977-cf6421a7-232d-4538-a3a8-e58cdc3c1276.png">

- `hippo4j-ui/src/views/hippo4j/threadpool/index.vue`

- `hippo4j-ui/src/views/hippo4j/instance/index.vue`

**Comment by Ronan1024** [comment]
claim

**Comment by pirme** [comment]
@liushu209 welcome

**Comment by magestacks** [comment]
@liushu209 请问最近有时间完成该 Issue 么？

**Comment by Ronan1024** [comment]
有发自我的 iPad在 2023年4月1日，18:09，马称 ***@***.***> 写道：﻿
@liushu209 请问最近有时间完成该 Issue 么？
