### ISSUE TITLE
容器线程池查看详情拒绝策略为空

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1070]
确定拒绝策略为空的原因，如果是问题请修复它。

<img width="1643" alt="image" src="https://user-images.githubusercontent.com/77398366/222149404-93589dac-f7e4-4863-975b-77b32f31c774.png">

**Comment by jianlai5** [comment]
认领

**Comment by pirme** [comment]
@jianlai5 welcome

**Comment by jianlai5** [comment]
Fixes #1070

reason:
This is an exceptional case and cannot be repeated.

容器线程池查看详情拒绝策略为空
