### ISSUE TITLE
Hystrix Adapter 支持 hippo4j config

### ISSUE THREAD

**Issue by klook-tech-jayyang** [opengoofy/hippo4j#1074]
### 描述你想要的功能

目前三方框架线程池 Hystrix adapter 仅支持 hippo4j server，希望也支持 hippo4j config，可以在 grafana 上监控到。

**Comment by klook-tech-jayyang** [comment]
需要提供 HystrixThreadPoolAdapter 的另一个实现版本

**Comment by pirme** [comment]
我记得三方框架线程池适配对于 Hippo4j Server 和 Config 是通用的，你的另一个实现版本指的是？

**Comment by klook-tech-jayyang** [comment]
> 我记得三方框架线程池适配对于 Hippo4j Server 和 Config 是通用的，你的另一个实现版本指的是？

@pirme HystrixThreadPoolAdapter 需要 ThreadPoolAdapterRegisterAction，该类的实现在 hippo4j-spring-boot-starter 中，当引入 hippo4j-config-spring-boot-starter 和 hippo4j-spring-boot-starter-adapter-hystrix 时，服务无法启动。

是否可以提供另一个实现版本来支持 hippo4j config？

**Comment by pirme** [comment]
@shining-stars-lk 宽哥看呢，这里确实是个问题。因为 Hystrix 的线程池特殊性，所以有部分依赖在 Server 的包中，如果想要 Config 模式中启动，应该如何改动？ 

@jjiey 你有什么想法么？

**Comment by klook-tech-jayyang** [comment]
> @shining-stars-lk 宽哥看呢，这里确实是个问题。因为 Hystrix 的线程池特殊性，所以有部分依赖在 Server 的包中，如果想要 Config 模式中启动，应该如何改动？
> 
> @jjiey 你有什么想法么？

@pirme 是否可以提供两个实现版本，一个使用 ThreadPoolAdapterRegisterAction 供 hippo4j server 使用（现有的实现），另一个不用 ThreadPoolAdapterRegisterAction 供 hippo4j config 使用。当然两个实现会有很多相同之处，可以使用模版。然后在 HystrixAdapterAutoConfiguration 中根据 BootstrapProperties 或 BootstrapConfigProperties 来注入不同的实现

**Comment by pirme** [comment]
@jjiey 这是一个很好的想法。因为 Hippo4j Server SDK 中主要是向 Server 服务 Push 数据，我理解和 Config 模式会存在很大的差别。所以，我建议先不要抽象，各自实现即可。

Hystrix 第一版本是由 @shining-stars-lk 完成，不过他最近有点忙， @jjiey  你有兴趣开发这个组件么？

**Comment by klook-tech-jayyang** [comment]
> @jjiey 这是一个很好的想法。因为 Hippo4j Server SDK 中主要是向 Server 服务 Push 数据，我理解和 Config 模式会存在很大的差别。所以，我建议先不要抽象，各自实现即可。
> 
> Hystrix 第一版本是由 @shining-stars-lk 完成，不过他最近有点忙， @jjiey 你有兴趣开发这个组件么？

可以指派给我。

另外，我理解这里对于 Server 和 Config 模式的数据收集上报流程是一样的（通过 ThreadPoolAdapter#getThreadPoolStates 收集数据，通过 ThreadPoolMonitor 上报数据），而 Server 只是比 Config 多了用 ThreadPoolAdapterRegisterAction 向 Server 服务 Push 数据。

**Comment by pirme** [comment]
是的，那这里先按照你的实际逻辑实现一版提个 PR 看看。

**Comment by zhbdesign** [comment]
threadpool内使用了hystrixcommond处理一些逻辑，hystrixcommond内的mdc不生效，无法获取traceId，有办法解决吗

**Comment by klook-tech-jayyang** [comment]
hi @zhbdesign, Hippo4j 只是对 Hystrix 线程池进行增强，并不对线程进行变更。

[Hystrix](https://github.com/Netflix/Hystrix/wiki/Plugins#concurrencystrategy) 中提供了 [HystrixConcurrencyStrategy](http://netflix.github.io/Hystrix/javadoc/index.html?com/netflix/hystrix/strategy/concurrency/HystrixConcurrencyStrategy.html) 接口可以在执行前装饰 Callable 来实现复制线程状态，具体可查看 wrapCallable() 方法。
