### ISSUE TITLE
客户端的容器线程池无法注册到K8S上部署的Server

### ISSUE THREAD

**Issue by zjHe** [opengoofy/hippo4j#1082]
### 你使用了哪个项目？hippo4j config 还是 hippo4j server?

我使用的是hippo4j server，k8s部署

### 你使用了哪个版本？

1.4.3

### 问题描述
1. 本地客户端的undertow线程池无法注册到server上面，普通线程可以注册，并且能看到线程信息（server访问客户端），也能修改（客户端长轮询server），说明网络互通。我在客户端，直接调用/web/base/info接口，其实是可以拉取到undertow的信息的。
2. 出现上面的问题之后，怀疑是客户端接的不对，我做了个实验，我本地起server，本地客户端连接server，发现是可以注册上去的，一切都正常。

**Comment by magestacks** [comment]
这里提供几点排查思路：

1. 确定应用 Web 容器一定是 Undertow 么？
2. 查看 Server 请求客户端 URL 是否被拦截。
3. 可以在 `cn.hippo4j.springboot.starter.controller.WebThreadPoolController#getPoolBaseState` 源码 Debug 打印一些日志，看看是否有发现。
