### ISSUE TITLE
hippo4j server无法清除重启后遗留的client instance线程配置缓存信息

### ISSUE THREAD

**Issue by tudou0806** [opengoofy/hippo4j#1083]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/community/faq)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?
hippo4j server
### 你使用了哪个版本？
1.4.3
### 预期行为
client端在重启后，hippo4j server线程实例列表中应该剔除掉无效的实例线程池配置信息
### 实际行为
在client端重启或者发版后，hippo4j server线程实例列表中还是存在着无效的实例线程池配置信息，无法自动删除，只能重启hippo4j server
### 原因分析（如果可以）
1. 我这边的项目比较大，同时支持的数据源比较多（2-4个，扫描的bean也比较多）
2. 跟踪client源码发现，在hippo4j 初始化ClientWorker的时候，会开启一个定时任务（长轮训机制），获取server的线程池更新信息
3. 在这个定时任务线程中，有个CountDownLatch  awaitApplicationComplete ，这个开始是阻塞的，需要等到整个应用启动完成时，才会释放（但是由于系统是多数据源，在第一个数据源启动完成后，我看这个CountDownLatch 就释放了，所以就去server中获取线程池的配置，由于在server还未注册实例，所以就会把线程池配置缓存起来）；
4. 如果这个时候关闭掉client，那么那部分缓存的线程池配置就无法清除掉了；
5. 无法删除掉，因为client每次启动，对应的uuid是不一样的，server的淘汰机制也没法找到那部分半注册的缓存配置
6. 因此，我觉得根本问题可能就出现在这里

### 问题重现步骤
1. 使用的项目尽量复杂一些，比如多加几个数据源（多创建几个DataSource 的Bean），多创建一些动态线程池
2. 第一次待项目完全启动，client完整注册到hippo4j server中
3. 关闭client端（kill -9）
4. 重启client端，在hippo4j 线程池实例列表中观察到未完整注册的实例信息时，关闭client端（kill -9）
5. 再次完整重启client端，完整注册到hippo4j中
6. 点击搜索没有线程池对应的实例列表，发现第一次正常启动的实例已经删除，第二次未完整启动的实例信息一直存在，第三次启动的实例信息正常展示 
### 用于重现此问题的示例代码（例如 GitHub 链接）
由于是公司项目，无法提供

**Comment by magestacks** [comment]
已修复 https://github.com/opengoofy/hippo4j/pull/1127
