### ISSUE TITLE
DynamicThreadPoolRegisterParameter#threadFactory序列化异常

### ISSUE THREAD

**Issue by wulangcode** [opengoofy/hippo4j#1085]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/community/faq)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?
hippo4j config、hippo4j server
### 你使用了哪个版本？
最新版本
### 预期行为
客户端注册服务端不报错。
### 实际行为
<img width="1760" alt="image" src="https://user-images.githubusercontent.com/48200100/223440606-eca19320-a12b-4ff0-843f-e570017c51cd.png">

```
org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class java.util.concurrent.ThreadFactory]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.util.concurrent.ThreadFactory` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (PushbackInputStream); line: 1, column: 295] (through reference chain: cn.hippo4j.common.model.register.DynamicThreadPoolRegisterWrapper["parameter"]->cn.hippo4j.common.model.register.DynamicThreadPoolRegisterParameter["threadFactory"])
```

### 原因分析（如果可以）
ThreadFactoryBuilder#build(cn.hippo4j.common.design.builder.ThreadFactoryBuilder) 中使用了`Executors.defaultThreadFactory()`

### 问题重现步骤
1.拉取最新版本代码，删除服务端数据库中数据，走服务器中未定义的动态线程池配置的逻辑，让客户端自己注册
2.启动服务端
3.启动`hippo4j-spring-boot-starter-example`示例模块

### 解决方案
1. 在`DynamicThreadPoolRegisterParameter#threadFactory`的属性上加上,`@JsonIgnore`不进行序列化。查看服务端接口并未使用客户端上传上来的`ThreadFactory`字段。

**Comment by magestacks** [comment]
客户端线程池注册服务端有单独的 API，该流程是否走的自主注册 API？

**Comment by wulangcode** [comment]
`GlobalThreadPoolManage.dynamicRegister(registerWrapper);`
![image](https://user-images.githubusercontent.com/48200100/223968157-50ed8004-ca44-4570-8fe3-b4ac3a569e28.png)

**Comment by magestacks** [comment]
Fixed
