### ISSUE TITLE
IdentifyUtil 77 lines of StringBuilder can use string + instead to simplify the code

### ISSUE THREAD

**Issue by weihubeats** [opengoofy/hippo4j#1093]
## 需求建议
IdentifyUtil 77 lines of StringBuilder can use string + instead to simplify the code
请在提交问题之前回答这些问题，谢谢。

### 您的功能请求是否与问题有关？
no
### 描述你想要的功能
<img width="881" alt="image" src="https://user-images.githubusercontent.com/42484192/224330895-4d88b706-d552-4404-8d7c-e8895f010189.png">
<img width="402" alt="image" src="https://user-images.githubusercontent.com/42484192/224330945-cf75de4f-cfa3-48dd-9c91-2dc5372fae0c.png">

**Comment by ShengTongSun** [comment]
I can do  it.

**Comment by GM-Studio** [comment]
认领

**Comment by pirme** [comment]
@ShengTongSun welcome

**Comment by pirme** [comment]
> 认领

抱歉，另一位先评论认领的。
