### ISSUE TITLE
DynamicThreadPoolAdapterChoose can use lambda to simplify the code

### ISSUE THREAD

**Issue by weihubeats** [opengoofy/hippo4j#1094]
## 需求建议
DynamicThreadPoolAdapterChoose can use lambda to simplify the code
请在提交问题之前回答这些问题，谢谢。

### 您的功能请求是否与问题有关？
no
### 描述你想要的功能
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/42484192/224331296-94bbc922-3d22-488b-9fff-2227eecdf012.png">

```java
        dynamicThreadPoolAdapterOptional.ifPresent(dynamicThreadPoolAdapter -> dynamicThreadPoolAdapter.replace(executor, dynamicThreadPoolExecutor));

```

**Comment by 2595001965** [comment]
认领

**Comment by pirme** [comment]
@2595001965 welcome
