### ISSUE TITLE
The use of {} in String.format in ThreadFactoryBuilder does not work, we need to change it to %s

### ISSUE THREAD

**Issue by weihubeats** [opengoofy/hippo4j#1095]
## 需求建议
The use of {} in String.format in ThreadFactoryBuilder does not work, we need to change it to %s
请在提交问题之前回答这些问题，谢谢。

### 描述你想要的功能
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/42484192/224332542-e46420b6-6a39-4485-ab87-ef778d1dab7b.png">

```java
            throw new IllegalArgumentException(String.format("Thread priority (%s) must be >= %s", priority, Thread.MIN_PRIORITY));

```

**Comment by akballal** [comment]
Hi, I would like to work on this. Could you please assign this to me ?

**Comment by magestacks** [comment]
@akballal Welcome.
