### ISSUE TITLE
核心阻塞队列枚举 BlockingQueueTypeEnum 增加单元测试

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1096]
`cn.hippo4j.common.executor.support.BlockingQueueTypeEnum` 增加以下方法单元测试：

- `cn.hippo4j.common.executor.support.BlockingQueueTypeEnum#createBlockingQueue(java.lang.String, java.lang.Integer)`
- `cn.hippo4j.common.executor.support.BlockingQueueTypeEnum#createBlockingQueue(int, java.lang.Integer)`
- `cn.hippo4j.common.executor.support.BlockingQueueTypeEnum#getBlockingQueueNameByType`
- ``cn.hippo4j.common.executor.support.BlockingQueueTypeEnum#getBlockingQueueTypeEnumByName`

```txt
备注：
Commit Log 使用英文，其它参考 [贡献规约](https://hippo4j.cn/community/contributor-guide)。
```

**Comment by LiXuemin** [comment]
认领

**Comment by pirme** [comment]
@LiXuemin welcome
