### ISSUE TITLE
核心阻塞队列枚举 BlockingQueueTypeEnum 代码优化

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1097]
`cn.hippo4j.common.executor.support.BlockingQueueTypeEnum` 优化列：

- 该队列必须有界、该队列不支持有界 修改为英文。
- `customeQueue` 字段名称错误，修改为 `customerQueue`。
- `cn.hippo4j.common.executor.support.BlockingQueueTypeEnum#LINKED_BLOCKING_DEQUE` 需要支持 `capacity`，避免生成无界队列。
- `type` 和 `name` 字段修改为 final 修饰。
- `typeToEnumMap` 和 `nameToEnumMap` 修改为 final 修饰；以及转为静态字段命名方式，比如 `TYPE_TO_ENUM_MAP`。

```txt
备注：
Commit Log 使用英文，其它参考 [贡献规约](https://hippo4j.cn/community/contributor-guide)。
```

**Comment by LiXuemin** [comment]
认领

**Comment by pirme** [comment]
@LiXuemin welcome
