### ISSUE TITLE
fix:NotSupportedException

### ISSUE THREAD

**Issue by wulangcode** [opengoofy/hippo4j#1101]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/community/faq)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?
hippo4j config
### 你使用了哪个版本？
develop
### 预期行为
项目正常启动
### 实际行为
<img width="1619" alt="image" src="https://user-images.githubusercontent.com/48200100/224525318-a103d906-9100-431e-8ec5-635371d6f810.png">

### 原因分析（如果可以）
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/48200100/224525357-7294c0fb-7ea2-486e-815f-5293482d937b.png">

`NotSupportedException`这个异常有存在的必要吗？或者我们只用给一个提示性信息，而不是`RuntimeException`

### 问题重现步骤
启动`hippo4j-spring-boot-starter-example`

**Comment by wulangcode** [comment]
#1025

**Comment by magestacks** [comment]
对于队列设置有界或无界，我认为用户应该在创建时做到有这方面认知，避免因为用户的不留意，而造成生产的事故。

**Comment by wulangcode** [comment]
输出提示就行了吧，如果有人用了前面的版本，也没做到向前兼容。

**Comment by magestacks** [comment]
向前兼容是个很重要的点👍，这一版本改为输出提示 WRAN 级别提示吧。

**Comment by magestacks** [comment]
已修复
