### ISSUE TITLE
hippo4j-config-spring-boot-starter1.4.3配置nacos无法动态刷新线程池的参数配置

### ISSUE THREAD

**Issue by BigBigFeiFei** [opengoofy/hippo4j#1110]
### 你使用了哪个项目？hippo4j config 还是 hippo4j server?
hippo4j config 使用的是如下版本：

>       ` <dependency>
>             <groupId>cn.hippo4j</groupId>
>             <artifactId>hippo4j-config-spring-boot-starter</artifactId>
>             <version>1.4.3-upgrade</version>
>         </dependency>`

### 你使用了哪个版本？
nacos客户端引入的依赖

>       `<dependency>
>             <groupId>com.alibaba.cloud</groupId>
>             <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
>             <version>2.2.5.RELEASE</version>
>         </dependency>`
nacos的客户端版本是：1.4.1
nacos服务端的版本用的是2.0.3
![image](https://user-images.githubusercontent.com/35337873/225218258-24ae44d2-3e26-40dc-96be-f4f96c507249.png)

### 预期行为
![image](https://user-images.githubusercontent.com/35337873/225218470-a68eff59-6159-4ac4-a28c-96f7564d73bc.png)
nacos的hippo4j-nacos.yaml配置内容如下：

说明：以下的yml配置由于粘贴过来导致格式有点不美观，但是就是实际的配置：
> spring:
>   dynamic:
>     thread-pool:
>       executors:
>         - active-alarm: 80
>           alarm: false
>           allow-core-thread-time-out: false
>           blocking-queue: ResizableCapacityLinkedBlockingQueue
>           capacity-alarm: 80
>           core-pool-size: 21
>           execute-time-out: 800
>           keep-alive-time: 6691
>           maximum-pool-size: 40
>           queue-capacity: 1024
>           rejected-handler: AbortPolicy
>           thread-name-prefix: message-consume
>           thread-pool-id: message-consume
>         - active-alarm: 80
>           alarm: false
>           allow-core-thread-time-out: false
>           blocking-queue: ResizableCapacityLinkedBlockingQueue
>           capacity-alarm: 80
>           core-pool-size: 2
>           execute-time-out: 800
>           keep-alive-time: 6691
>           maximum-pool-size: 4
>           queue-capacity: 1024
>           rejected-handler: AbortPolicy
>           thread-name-prefix: message-produce
>           thread-pool-id: message-produce
>       web:
>         core-pool-size: 64
>         enable: true
>         keep-alive-time: 1000
>         maximum-pool-size: 128

demo项目是如下工程结构：
![image](https://user-images.githubusercontent.com/35337873/225218771-bc5243b0-3738-4d27-be59-2813df8e7aed.png)
ThreadPoolConfig代码如下：
`package org.example.config;

import cn.hippo4j.core.executor.DynamicThreadPool;
import cn.hippo4j.core.executor.support.ThreadPoolBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.concurrent.ThreadPoolExecutor;

@Configuration
public class ThreadPoolConfig {

    @Bean
    @DynamicThreadPool
    public ThreadPoolExecutor messageConsumeDynamicExecutor() {
        String threadPoolId = "message-consume";
        ThreadPoolExecutor messageConsumeDynamicExecutor = ThreadPoolBuilder.builder()
                .threadFactory(threadPoolId)
                .threadPoolId(threadPoolId)
                .dynamicPool()
                .build();
        return messageConsumeDynamicExecutor;
    }

    @Bean
    @DynamicThreadPool
    public ThreadPoolExecutor messageProduceDynamicExecutor() {
        String threadPoolId = "message-produce";
        ThreadPoolExecutor messageProduceDynamicExecutor = ThreadPoolBuilder.builder()
                .threadFactory(threadPoolId)
                .threadPoolId(threadPoolId)
                .dynamicPool()
                .build();
        return messageProduceDynamicExecutor;
    }

}`
ThreadExcuteInfoController代码如下：
`package org.example.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.annotation.Resource;
import java.util.concurrent.ThreadPoolExecutor;

@RestController
@RequestMapping("/getInfo")
public class ThreadExcuteInfoController {

    @Resource
    private ThreadPoolExecutor messageConsumeDynamicExecutor;

    @GetMapping("/helloWorld")
    public String helloWorld() {
        int corePoolSize = messageConsumeDynamicExecutor.getCorePoolSize();
        return "helloWorld,corePoolSize:" + corePoolSize;
    }

}
`
bootstrap.yml配置如下：

> logging:
>   level:
>     root: DEBUG
> spring:
>   application:
>     name: hippo4j-config-nacos-spring-boot-starter-example
>   cloud:
>     nacos:
>       config:
>         extension-configs:
>           - data-id: hippo4j-nacos.yaml
>             group: DEFAULT_GROUP
>             refresh: true
>         password: nacos
>         server-addr:  xxxx:8848
>         username: nacos
>   dynamic:
>     thread-pool:
>       banner: true
>       config-file-type: yml
>       enable: true
>       monitor:
>         collect-interval: 5000
>         collect-types: micrometer
>         enable: false
>         initial-delay: 10000
>         thread-pool-types: dynamic,web
>       nacos:
>         data-id: hippo4j-nacos.yaml
>         group: DEFAULT_GROUP
>       notify-platforms:

上面两个类启动的时候都进行了包扫描，可以注入到springBoot的容器中，
 期望行为是浏览器访问：http://127.0.0.1:8080/getInfo/helloWorld
获取到message-consume线程池的核心线程数应该是nacos上hippo4j-nacos.yaml配置文件中配置的21,但是实际上返回了一个30的值，这个就很离谱了。

### 实际行为
![image](https://user-images.githubusercontent.com/35337873/225219863-1148cedb-770c-4e6d-ad93-f8c29c135c96.png)

### 原因分析
控制台打印的一个很有意思的日志是：
2023-03-15 14:00:15.861 DEBUG 10968 --- [10.0.41.24_8848] c.a.n.c.c.impl.ConfigHttpClientManager   : HTTP method: POST, url: http://10.0.41.24:8848/nacos/v1/cs/configs/listener, body: {Listening-Configs=hippo4j-config-nacos-spring-boot-starter-example.propertiesDEFAULT_GROUPhippo4j-config-nacos-spring-boot-starter-exampleDEFAULT_GROUP29b4ebf10f1875f09c92e0a51f567e9bhippo4j-nacos.yamlDEFAULT_GROUP, accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTY3ODg3NTQyN30.p05ckmeAaTs2OeMutK2VmZBKQpWdF_dZ12kcVSj0pIw}
2023-03-15 14:00:15.861 DEBUG 10968 --- [10.0.41.24_8848] c.a.n.c.c.impl.ConfigHttpClientManager   : Execute via interceptors :[com.alibaba.nacos.client.config.impl.ConfigHttpClientManager$LimiterHttpClientRequestInterceptor@19593091]
2023-03-15 14:00:15.861 DEBUG 10968 --- [10.0.41.24_8848] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@53a16d316 pairs: {POST /nacos/v1/cs/configs/listener HTTP/1.1: null}{Content-Type: application/x-www-form-urlencoded;charset=UTF-8}{Accept-Charset: UTF-8}{Accept-Encoding: gzip}{Client-AppName: unknown}{Client-RequestTS: 1678860015860}{Client-RequestToken: 5a252aca6fb323ad1c724ca1dfe76088}{Client-Version: 1.4.1}{exConfigInfo: true}{RequestId: 57d1fd53-715a-4d9a-bfa7-184016a022ec}{Long-Pulling-Timeout: 30000}{User-Agent: Java/1.8.0_321}{Host: 10.0.41.24:8848}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}{Content-Length: 363}
1)估计一直拉取没有拉取到，由于我的nacos是公司内网的nacos，连接测试环境是需要vpn的，所以会不会是有多块网卡导致连接nacos拉取nacos的连接失败，
2)估计还有一个原因就是nacos的客户端和端的版本不一致导致，nacos的服务端用版本是2.0.3，而nacos依赖的客户端的版本是1.4.1，上面的代码和操作都是根据官方文档来操作的：
https://hippo4j.cn/docs/user_docs/getting_started/config/hippo4j-config-start
具体是啥问题也不晓得，网络问题可以排除，看日志是发送了http请求的，但是很奇怪的是这个日志：Client-AppName: unknown

**Comment by pirme** [comment]
已测试，该问题属于无效问题，估计和他环境或者网络有关系

**Comment by BigBigFeiFei** [comment]
先在本地搭建本地网络环境，nacos服务端的版本需要用2.1.1版本是没有问题的，作者给了答复是：没有 2.x 的 nacos，直接用的 2.1.1，我给了他demo，他用nacos的服务端版本是2.1.1的本地网络环境是可以刷新的，所以各位老铁记得这个坑避一避哈

**Comment by BigBigFeiFei** [comment]
估计是nacos服务端2.0.3有bug,换成2.1.1就可以了

**Comment by BigBigFeiFei** [comment]
这个问题不是nacos服务端版本的问题，是本地网络的问题，本地网路的网络的网卡有多张，windwos安装了docker也会虚拟好几张网卡，同时使用vpn链接公司内网的nacos也会有一张网卡或者是配使用置阿里云上的nacos可以外网访问，但是你的主机是跟阿里云的nacos的网路不是在同一个网段里面，所以最好是在本机只有一张网卡的请情下，不使用docker安装nacos和mysq5.7.16数据库，要安装是用二进制包安装，或者是在windwos上安装一个虚拟机，在虚拟机上安装docker、nacos和mysql使用host网络启动，或者使用两台主机都在同一个网路里面这种就不会有网路问题了，然后在验证看看。

**Comment by BigBigFeiFei** [comment]
这个不是网路的问题，是extension-configs的拓展配置不会热更新，我使用的springBoot的版本是：2.3.12.RELEASE，我在demo中验证了nacos原本的动态刷新是ok的：
‘@RefreshScope
@RestController
@RequestMapping("/getInfo")
public class ThreadExcuteInfoController {

    @Value("${a:1}")
    private String a;

    @Value("${b:2}")
    private String b;

    @Resource
    private ThreadPoolExecutor messageConsumeDynamicExecutor;

    @GetMapping("/helloWorld")
    public String helloWorld() {
        int corePoolSize = messageConsumeDynamicExecutor.getCorePoolSize();
        return "helloWorld,corePoolSize:" + corePoolSize;
    }

    @GetMapping("/helloWorld2")
    public String helloWorld2() {
        return "helloWorld,a:" + a + ",b:" + b;
    }

}
’
在nacos的主配置文件中配置了a,b两个变量，修改会刷新(http://ip:8080/getInfo/helloWorld2)，然后将b变量移动到拓展配置中，在拓展配置中修改b的值发现不会热更新，然后试图注释项目中的extension-configs配置，直接把动态数据源的配置之前的拓展配置配置到主配置中然后去访问
http://ip:8080/getInfo/helloWorld
这个发现 message-consume线程池的核心线程数还是30，简直就是离谱，难道这个不是bug么？
