### ISSUE TITLE
ZipkinExecutorAdapter 可能出现空指针异常

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1114]
代码类：

- `cn.hippo4j.core.executor.support.adpter.ZipkinExecutorAdapter`

可能出现空指针异常的代码片段：

```java
public boolean matchSuper(Object executor) {
    if (Objects.equals(MATCH_CLASS_NAME, executor.getClass().getName())) {
        return true;
    } else {
        return Objects.equals(MATCH_CLASS_NAME, executor.getClass().getSuperclass().getName());
    }
}
```

其中 else 流程 `executor.getClass().getSuperclass().getName()` 可能存在空指针，使用 `Optional` 进行优化。

备注：

Commit Log 使用英文，其它参考 [贡献规约](https://hippo4j.cn/community/contributor-guide)

**Comment by yult97** [comment]
Check
