### ISSUE TITLE
Server服务端出现Active参数为空问题

### ISSUE THREAD

**Issue by zjHe** [opengoofy/hippo4j#1121]
## BUG 报告

在客户端kill -15 或者 kill -2 下线时，server端有概率出现Active参数为空的情况

![active空](https://user-images.githubusercontent.com/34431616/225506628-08792a8f-3410-4796-8c37-f15174a8f52f.png)

客户端服务下线日志，327dc26****这个实例。

![关闭](https://user-images.githubusercontent.com/34431616/225508182-13228571-8d08-4de8-87de-e6890e330148.png)

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?

使用的是hippo4j server

### 你使用了哪个版本？

1.4.3-upgrade版本

### 实际行为

下线时，客户端DiscoveryClient的destroy方法会向server注销服务，注销服务后，server服务对应的这个客户端实例会下线消失，但是过了一会，实例又注册上去了，且有几率出现Active为空的情况。看了客户端的日志后，发现以下情况，在客户端告知服务端下线之后，又会重新注册上去。

![renew](https://user-images.githubusercontent.com/34431616/225508464-d00ef847-44c2-43cb-9eeb-aeedb677ba4e.png)

### 原因分析

该方法是定时隔点续期，会导致重新注册，但重新注册也会带上Active的信息，哪怕重新注册了，过一会，也会被定时清理掉，不该出现Active为空的情况，可以优化DiscoveryClient的destroy方法的调用，shutdown掉该线程，避免再注册

![image](https://user-images.githubusercontent.com/34431616/225508636-1e44efa2-5d00-4ac8-b02d-e055cce043d9.png)

最后调查的原因ClientWorker中调度线程checkUpdateDataIds方法导致，DiscoveryClient的destroy之后，worker又进行了长轮询，将配置信息带到了server（这部分信息恰好是没有active的），虽然woker里面的isHealthStatus方法有个参数clientShutdownHook是判断客户端是否shutdown，但是这个钩子函数的调用顺序没办法决定，DiscoveryClient的destory方法是另一个钩子函数执行的，有概率会出现先调用完destroy之后，再调用修改clientShutdownHook的钩子函数。

![image](https://user-images.githubusercontent.com/34431616/225510177-2903bc14-0447-4cb3-8b69-c12bdff78f91.png)
 
### 问题重现步骤

由于我们服务需要destroy的组件较多，调用DiscoveryClient.destroy之后，还要大概30s才能destroy掉其他的组件，这时候就容易出现问题。

问题重现步骤可以自己修改代码模拟

![image](https://user-images.githubusercontent.com/34431616/225511591-7d3d2ad0-0316-4736-b647-0115588cfd59.png)

### 解决思路

只要保证DiscoveryClient.destroy的逻辑关闭前，结束掉worker。

![image](https://user-images.githubusercontent.com/34431616/225511876-750826d4-e7c1-472e-97b5-bcc5998b3e9d.png)

destory 方法中加上

![image](https://user-images.githubusercontent.com/34431616/225512039-b85e30e9-e730-46ef-b86a-71adb8d4e8de.png)

woker的run方法中

![image](https://user-images.githubusercontent.com/34431616/225511841-96b0064f-5b31-4901-85d4-be0aa530fd40.png)

**Comment by pirme** [comment]
内容同 [/issues/979](https://github.com/opengoofy/hippo4j/issues/979)

可以提个 PR，大家一起 Review 下逻辑。

**Comment by linlinjie** [comment]
牛
