### ISSUE TITLE
关于ISSUE#1106产生的背景说明

### ISSUE THREAD

**Issue by yanrongzhen** [opengoofy/hippo4j#1126]
## 背景
在SpringBoot 1.5.x版本当中, 关于Web容器的获取和操作的api, 与SpringBoot 2.x版本(目前Hippo4j使用的主要版本)完全不兼容.
因此需要针对SpringBoot1.5.x版本做一个特定版本的实现, 以便可以操作web容器当中的线程池.

## 目标
通过类设计方法, 抽象和复用公共部分, 将具体针对特定版本的实现, 沉淀到下层各自版本模块当中.

## 方法
由于1.x已经开启一个定制化模块来进行适配(hippo4j-config-spring-boot-1x-starter), 将web容器的版本适配工作放在此模块当中.

其中, 类设计简化图示如下:
![image](https://user-images.githubusercontent.com/106363931/225616441-12e6ab5f-c6e6-4ea4-826f-39fb0ec9888b.png)

**Comment by magestacks** [comment]
👍

**Comment by magestacks** [comment]
可以将该 Issue 内容合并到 #1106 中

**Comment by yanrongzhen** [comment]
@magestacks 合并完毕
