### ISSUE TITLE
控制台前端国际化开发

### ISSUE THREAD

**Issue by pirme** [opengoofy/hippo4j#1128]
贡献文档：https://sourl.cn/5TD4Fq

国际化文档：[国际化翻译表格](https://www.yuque.com/magestack/duzmb2/gk0a1a?singleDoc#9mEC《Hippo4j国际化翻译文件》)

前端代码地址：`/hippo4j-ui`

备注：

- 目前国际化已有部分支持，需要按照国际化文档支持全部页面。

- Commit Log 使用英文，其它参考 [贡献规约](https://hippo4j.cn/community/contributor-guide)。

**Comment by Svamei** [comment]
我可以试试，这将会是我第一次参加开源项目。

**Comment by pirme** [comment]
@Svamei 欢迎，这个任务我先不指派给你，麻烦先评估下是否有把握在一周内完成，因为马上要发的 1.5.0 依赖该任务。

时间如果没问题，可以以页面为单位，分别提交 PR。

**Comment by Svamei** [comment]
好的，我有信心一周内可以完成。

**Comment by pirme** [comment]
@Svamei Welcome

**Comment by magestacks** [comment]
感谢你的贡献，方便的话可以加我个微信

![image](https://user-images.githubusercontent.com/77398366/229418571-abeee465-d047-4005-83a8-2f8f656f18ea.png)
