### ISSUE TITLE
prometheus 不能正常采集 hystrix 线程池 queue.capacity 数据

### ISSUE THREAD

**Issue by klook-tech-jayyang** [opengoofy/hippo4j#1129]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/community/faq)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?

hippo4j config

### 你使用了哪个版本？

最新版本

### 预期行为

prometheus 正常采集 hystrix 线程池数据

### 实际行为

prometheus 采集 hystrix 线程池数据报 warn（NPE）: 
Failed to apply the value function for the gauge 'adapter.thread-pool.queue.capacity'. Note that subsequent logs will be logged at debug level.

### 原因分析（如果可以）

`HystrixThreadPoolAdapter#getThreadPoolState` 中没有 `setBlockingQueueCapacity` 导致

**Comment by klook-tech-jayyang** [comment]
assign me pls

**Comment by magestacks** [comment]
@jjiey welcome
