### ISSUE TITLE
Should the thread pool alarm default be false?

### ISSUE THREAD

**Issue by klook-tech-jayyang** [opengoofy/hippo4j#1131]
## 问题支持

在开始报告问题之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/community/faq)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?

hippo4j config

### 你使用了哪个版本？

latest

### 预期行为

正常启动

### 实际行为

NPE

### 原因分析（如果可以）

alarm 参数是否应该默认为 false 好些？

![image](https://user-images.githubusercontent.com/29424908/226318551-e6fe991b-b1aa-4718-a92f-cfe72a08e832.png)

当用户不指定 alarm 时默认为 true，然后又没有指定 notify-platforms 参数，后续遍历时会 NPE

![image](https://user-images.githubusercontent.com/29424908/226321309-4ae426c6-23d7-48ea-b007-783857e95543.png)

或者遍历前判断一下 null

**Comment by magestacks** [comment]
@jjiey 是否可以帮忙优化该问题？如果可以的话，请充分测试对应流程，包括动态刷新通知等流程

**Comment by klook-tech-jayyang** [comment]
> @jjiey 是否可以帮忙优化该问题？如果可以的话，请充分测试对应流程，包括动态刷新通知等流程

ok, assign me pls.

**Comment by magestacks** [comment]
@jjiey Welcome.

**Comment by magestacks** [comment]
@jjiey 最近有时间完成该 Issue 么？即将发版 1.5.0

**Comment by magestacks** [comment]
@jjiey 已迁移 1.5.1 版本

**Comment by klook-tech-jayyang** [comment]
不好意思处理晚了些，看了下代码，除了 alarm 为 true 时会通知，配置中心修改配置也会通知（也有可能触发 NPE），所以建议修改将 notifyPlatforms 初始化为 emptyListemp，马哥看呢 @magestacks

**Comment by magestacks** [comment]
可以按照你的想法提交个 PR 先看看。

**Comment by yanrongzhen** [comment]
@jjiey 有测试过SpringBoot1.x的情况么? 我发现config模式, springboot1.x如果加了这个默认值, 主流程会不通
