### ISSUE TITLE
线程池实例无数据

### ISSUE THREAD

**Issue by luobaorui** [opengoofy/hippo4j#1137]
## 问题支持

在开始报告问题之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/community/faq)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?

hippo4j server模式

### 你使用了哪个版本？

1.4.3-upgrade

### 预期行为

线程池实例可以发现服务自动注册的数据

### 实际行为

线程池实例无数据

### 问题重现步骤

已按接入流程配置，并在线程池管理页面添加线程池

**Comment by pirme** [comment]
通过该描述，无法确定问题，可以提供个能复现问题的 Demo 工程。

**Comment by luobaorui** [comment]
![image](https://user-images.githubusercontent.com/129134296/228116405-efd6f891-5dea-43b3-8fb1-c33c8492551f.png)
![image](https://user-images.githubusercontent.com/129134296/228116526-13861fed-7eb4-4fa4-858b-fb31e4b0cf65.png)
![image](https://user-images.githubusercontent.com/129134296/228117011-126125f2-411c-48d5-aba0-06b75284f7bf.png)
![image](https://user-images.githubusercontent.com/129134296/228116622-1d76d91b-24dd-49dc-8e06-a56276ec8a4b.png)
![image](https://user-images.githubusercontent.com/129134296/228116755-4fc92855-7a02-4001-afe3-5a0eada80a8c.png)

**Comment by luobaorui** [comment]
![image](https://user-images.githubusercontent.com/129134296/228117408-23871004-117e-422f-8131-55999649356c.png)

**Comment by luobaorui** [comment]
![image](https://user-images.githubusercontent.com/129134296/228117924-69a55800-55c8-47ce-904c-3ebe881ad8eb.png)

**Comment by pirme** [comment]
问题已解决，用户操作有误导致。

**Comment by BruceAn1978** [comment]
> 

怎么解决的？server和项目启动都没有报错，server端的实例列表无任何数据。
