### ISSUE TITLE
优化执行时间超时 executeTimeOut 为空或 <= 0 的场景

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1148]
代码位置：

- `cn.hippo4j.core.plugin.impl.TaskTimeoutNotifyAlarmPlugin#processTaskTime`

如果 `executeTimeOut` 为空或 <= 0 直接 return 即可。

**Comment by sususama** [comment]
Hi, @magestacks 好的，我将会尝试解决这个问题。

**Comment by magestacks** [comment]
@sususama Welcome
