### ISSUE TITLE
控制台国际化必填项提示错误

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1152]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/community/faq)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?

hippo4j server

### 你使用了哪个版本？

1.5.0-SNAPSHOT

### 预期行为

根据国际化标识展示对应的提示语

### 实际行为

未根据国际化标识展示对应的提示语

**Comment by Svamei** [comment]
是图片中所出现的问题吗？可以指派给我。
![Snipaste_2023-04-13_20-31-03](https://user-images.githubusercontent.com/41992090/231761041-5ff95f9a-7a47-4c6e-bb5e-08ec08e473ed.png)

**Comment by magestacks** [comment]
是的，这个是通用的问题，所有新增 & 修改操作都会出现。请问周六前是否能修复？如果时间来不及的话我就放到 1.5.1 版本。

**Comment by Svamei** [comment]
来的及

**Comment by magestacks** [comment]
👍
