### ISSUE TITLE
WeChat & LarkSend MessageHandler record failure result.

### ISSUE THREAD

**Issue by iwangjie** [opengoofy/hippo4j#1159]
## 需求建议

当MessageHandler通知失败时，希望记录通知结果，以帮助研发和运维人员检查预警通道是否配置正确。

### 描述你想要的功能

参考DingSendMessageHandler对其他的 cn.hippo4j.message.service.SendMessageHandler 预警实现提供异常信息打印。

**Comment by ishikaibin** [comment]
pls assign me

**Comment by iwangjie** [comment]
> pls assign me

good. looking forward to you pr.
