### ISSUE TITLE
Hippo4j 口令过长引起拒绝服务攻击的漏洞报告

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1167]
Issue 来自 山东大学网络空间安全学院（研究院）

以下为原文：

```txt
尊敬的开发团队：

   你们好！

   最近在使用贵司开发的hippo4j时发现程序并未对口令最长长度做出限制，这有可能导致拒绝服务攻击。我在自己的电脑中搭建了hippo4j环境并对其进行测试，具体细节请见附件。
   
    如果此问题确为一个安全问题，还请回复一封确认邮件，我将不胜感激！

INfinite，山东大学网络空间安全学院（研究院）
```

复现步骤：

<img width="996" alt="image" src="https://user-images.githubusercontent.com/77398366/232470714-a3580d25-2099-486b-9c16-7d3a53ca7f8d.png">

**Comment by ishikaibin** [comment]
pls assign me.

**Comment by ITXiaoShiTou** [comment]
@magestacks What do you think the reasonable password length should be set?

**Comment by ishikaibin** [comment]
@magestacks 
What do you think the reasonable password length should be set?
I tried the maximum password length of github,It prompts me:
Password is too long (maximum is 72 characters)

**Comment by magestacks** [comment]
@ITXiaoShiTou Welcome

**Comment by magestacks** [comment]
> @magestacks What do you think the reasonable password length should be set? I tried the maximum password length of github,It prompts me: Password is too long (maximum is 72 characters)

You can set it according to this rule and add restrictions to the front-end project
