### ISSUE TITLE
提交PR时自动触发CI检查

### ISSUE THREAD

**Issue by iwangjie** [opengoofy/hippo4j#1173]
修改CI配置文件支持在PR创建时自动运行检查，以避免一些简单的错误，提高PR审核效率。

欢迎认领

参考帮助：https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#pull_request_target

**Comment by pirme** [comment]
当前似乎是支持贡献者提交 PR 时进行检查的。

<img width="653" alt="image" src="https://user-images.githubusercontent.com/41976977/233553269-87d94308-daff-4eba-a234-766020916fe2.png">

**Comment by iwangjie** [comment]
> 

现在好像不行，我看提交PR没有自动进行检查。自动检查的话如下图：

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/23075587/233558211-a414c77c-9bc1-4602-b91f-9e718a506ed8.png">

**Comment by pirme** [comment]
可以尝试提交一次代码变动试试，目前文件变更并没有设置触发 CI

**Comment by DDreame** [comment]
我尝试修改配置文件以实现该请求，可见我的fork仓库：https://github.com/DDreame/hippo4j/pull/2

**Comment by magestacks** [comment]
经沟通，该 Issue 描述问题不存在，Close
