### ISSUE TITLE
[TASK] TaskRejectCountRecordPlugin add unit test.

### ISSUE THREAD

**Issue by iwangjie** [opengoofy/hippo4j#1180]
## 需求建议

请在提交问题之前回答这些问题，谢谢。

**Comment by Createsequence** [comment]
已有相关测试用例，参见 https://github.com/opengoofy/hippo4j/tree/develop/hippo4j-core/src/test/java/cn/hippo4j/core/plugin/impl

**Comment by iwangjie** [comment]
> 已有相关测试用例，参见 https://github.com/opengoofy/hippo4j/tree/develop/hippo4j-core/src/test/java/cn/hippo4j/core/plugin/impl

好👌🏻
