### ISSUE TITLE
There is no friendly prompt when the user does not exist.

### ISSUE THREAD

**Issue by HKMV** [opengoofy/hippo4j#1192]
### Which Project did you use? Hippo4j config or Hippo4j server?
Hippo4j server
### Which version did you use?
1.5.0
### Expected behavior
hint "User does not exist"
### Actual behavior
hint "Error"
### Cause analysis (if possible)
![image](https://user-images.githubusercontent.com/26456469/234465050-6b326ee5-f449-413f-9317-9f9f2e4ffe7b.png)

**Comment by magestacks** [comment]
Describe the steps in detail

**Comment by HKMV** [comment]
> Describe the steps in detail

Enter a non-existent user to log in

**Comment by magestacks** [comment]
Thanks, I think it's an optimization.

**Comment by HKMV** [comment]
> Describe the steps in detail

> Describe the steps in detail

I manually changed the database type from MySQL to H2;
It should be caused by not initializing the admin account during the initialization of the H2 database。

**Comment by lucca-suen** [comment]
Would it be possible for me to try to implement this function?

**Comment by lucca-suen** [comment]
> Thanks, I think it's an optimization.

Would it be possible for me to try to implement this function?

**Comment by magestacks** [comment]
@lucca-suen Welcome
