### ISSUE TITLE
[TASK] Change the global static constant of GlobalThreadPoolManage to a singleton object.

### ISSUE THREAD

**Issue by Createsequence** [opengoofy/hippo4j#1195]
## Demand advice

Adjust the global static constant `GlobalThreadPoolManage` to a singleton object.

### Is your function request related to the problem?

no

### Describe the function you want

**What**

Adjust the global static constant GlobalThreadPoolManage to a singleton object.

**Why**

The existing `GlobalThreadPoolManage` is actually used as a global static variable in the code, and this approach still feels problematic:

As a global static variable, it is not conducive to the writing of test cases;
As a core class, most components directly depend on its implementation rather than the interface, which is not convenient for later expansion;
The dependency relationship between components is not clear, and any class can directly modify it in a static method, which may have hidden dangers;
Therefore, it is hoped that `GlobalThreadPoolManage` can be separated into an independent interface + default implementation singleton, like `SingletonBeanRegistry` in Spring, and other components will hold and use the singleton as a member variable.

**How**

This adjustment may need to be divided into four parts:

Separate the `GlobalThreadPoolManage` interface and extract the existing code into the default implementation class;
Declare the default implementation as a Bean in the Spring configuration file;
All components that need to reference `GlobalThreadPoolManage` declare it as their own member variables and inject it in the constructor of the configuration class;
The existing related test cases need to be adjusted.

**Comment by Createsequence** [comment]
Based on similar ideas, should we also separate registry components such as `GlobalThreadPoolManage`, `ThreadPoolManager`, or `ThreadPoolAdapterRegister` into interfaces and default implementations, and allow related classes to use them by holding instances instead of directly using static variables?

Considering that in future versions, `hippo4j` may support non-Spring environments, callback interfaces such as `InitializingBean` or `ApplicationRunner` that some registry implementations strongly depend on may increase the difficulty of subsequent transformations. Therefore, using interface isolation to implement registry components may be necessary.

For example, if we want a `RejectedPolicy` manager, the existing implementation directly depends on `RejectedPolicyTypeEnum`, which only supports default built-in enum values and `CustomRejectedExecutionHandler` loaded via SPI in a static block. If a user wants to extend more ways, such as declaring their own custom rejection policies in the Spring context, or even removing some rejection policies(such as `DiscardPolicy`), `RejectedPolicyTypeEnum` will require significant changes.

Following this idea, we define the `RejectedPolicyTypeManager` interface for this part of the functionality, and it will be much easier to extend:

- We can make `RejectedPolicyTypeEnum` implement the `RejectedPolicyTypeManager` interface without any other changes;
- We can traditionally define a `RejectedPolicyTypeManager` based on `Map`, which allows us to freely implement add, delete, update and query operations;
- Based on the above `Manager`, we can further extend it using `BeanFactory`. If the `Map` cannot find it, we can directly search through `BeanFactory` or `SPI`;

Furthermore, we can refer to Spring's `ApplicationContext` to aggregate multiple registry tables of different components into a global context, and uniformly manage all dependencies to flexibly switch between different global configurations in different runtime environments.

**Comment by magestacks** [comment]
Agree with
