### ISSUE TITLE
Changing the configuration center mode on the official website Incorrect configuration

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1209]
Official website address:

https://hippo4j.cn/docs/user_docs/getting_started/config/hippo4j-config-more

File address:

- docs/docs/user_docs/getting_started/config/hippo4j-config-more.md
- docs/i18n/zh/docusaurus-plugin-content-docs/current/user_docs/getting_started/config/hippo4j-config-more.md

Change content:

`spring.dynamic.thread-pool.tomcat` -> `spring.dynamic.thread-pool.web`

**Comment by scorcism** [comment]
Hello, i would like to work on this
