### ISSUE TITLE
[Task] CheckStyle adds a rule that disallows importing *

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1223]
CheckStyle fails when importing * in code.

File: `dev-support/hippo4j_checkstyle.xml`

**Comment by liulinfei121** [comment]
认领

**Comment by magestacks** [comment]
@liulinfei121 Welcome

**Comment by liulinfei121** [comment]
cn.hippo4j:hippo4j-spring-boot-starter-adapter-rabbitmq:jar:1.5.0
cn.hippo4j:hippo4j-common:jar:1.5.0
cn.hippo4j:hippo4j-adapter-dubbo:jar:1.5.0
cn.hippo4j:hippo4j-adapter-alibaba-dubbo:jar:1.5.0
cn.hippo4j:hippo4j-adapter-kafka:jar:1.5.0
cn.hippo4j:hippo4j-adapter-hystrix:jar:1.5.0
cn.hippo4j:hippo4j-core:jar:1.5.0
cn.hippo4j:hippo4j-adapter-web:jar:1.5.0
cn.hippo4j:hippo4j-example-core:jar:1.5.0
cn.hippo4j:hippo4j-spring-boot-starter-adapter-web:jar:1.5.0
cn.hippo4j:hippo4j-spring-boot-starter:jar:1.5.0
cn.hippo4j:hippo4j-spring-boot-starter-example:jar:1.5.0
cn.hippo4j:hippo4j-config-spring-boot-starter:jar:1.5.0
cn.hippo4j:hippo4j-spring-boot-starter-es-monitor-example:jar:1.5.0
cn.hippo4j:hippo4j-config-nacos-spring-boot-starter-example:jar:1.5.0
cn.hippo4j:hippo4j-config-apollo-spring-boot-starter-example:jar:1.5.0
cn.hippo4j:hippo4j-config-zookeeper-spring-boot-starter-example:jar:1.5.0
cn.hippo4j:hippo4j-config-consul-spring-boot-starter-example:jar:1.5.0
cn.hippo4j:hippo4j-spring-boot-starter-adapter-rabbitmq-example:jar:1.5.0
cn.hippo4j:hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rabbitmq-example:jar:1.5.0
cn.hippo4j:hippo4j-spring-boot-starter-adapter-spring-cloud-stream-rocketmq-example:jar:1.5.0
cn.hippo4j:hippo4j-spring-boot-starter-adapter-rocketmq-example:jar:1.5.0
cn.hippo4j:hippo4j-spring-boot-starter-adapter-kafka-example:jar:1.5.0
cn.hippo4j:hippo4j-config-etcd-spring-boot-starter-example:jar:1.5.0
cn.hippo4j:hippo4j-config-spring-boot-1x-starter:jar:1.5.0
cn.hippo4j:hippo4j-config-nacos-spring-boot-1x-starter-example:jar:1.5.0
cn.hippo4j:hippo4j-config-apollo-spring-boot-1x-starter-example:jar:1.5.0
cn.hippo4j:hippo4j-rpc:jar:1.5.0
cn.hippo4j:hippo4j-config:jar:1.5.0
cn.hippo4j:hippo4j-agent-core:jar:1.5.0
cn.hippo4j:spring-plugin-common:jar:1.5.0
cn.hippo4j:spring-boot-1.x-plugin:jar:1.5.0
cn.hippo4j:spring-boot-2.x-plugin:jar:1.5.0
cn.hippo4j:thread-pool-plugin:jar:1.5.0
cn.hippo4j:apollo-plugin:jar:1.5.0
cn.hippo4j:hippo4j-agent-bootstrap:jar:1.5.0
