### ISSUE TITLE
建议在通知告警中加入所触发的runnable代码段指引

### ISSUE THREAD

**Issue by KhalilYeung** [opengoofy/hippo4j#1228]
需求建议
建议在通知告警中加入所触发的runnable代码段指引。

您的功能请求是否与问题有关？
无

描述你想要的功能
接手祖传老旧项目后，引入dynamic初衷想对占用线程池资源的业务代码进行优化甚至重构。
接入后虽然有想要的reject和timeout告警，但都没有指出具体触发告警的runnable是什么？在哪个类的哪一行提交的任务？
对业务并不是很熟悉的我，想优化但不知道先从哪里入手...

望采纳，谢谢~

**Comment by magestacks** [comment]
你的诉求，我理解是多个业务使用了一个线程池导致的，对么？

**Comment by KhalilYeung** [comment]
> 你的诉求，我理解是多个业务使用了一个线程池导致的，对么？

是的，例如有一个专门处理各模块数据固化的io等待型任务线程池，经常触发设置的超时时间，想找出是哪些task触发告警的

**Comment by magestacks** [comment]
Hippo4j 报警中存在一个灵活的链路字段，原理是获取当前线程上下文的一个变量，可以在任务开始前向这个变量赋值，就能解决你这个问题。

因为我在外面，你可以先看下 Hippo4j 的示例项目。

**Comment by HinsYang** [comment]
好的，看到实例项目里ThreadPoolBuilder还有个可配置的taskDecorator，自己也能实现TaskDecorator定制想要的

**Comment by KhalilYeung** [comment]
好的，看到实例项目里ThreadPoolBuilder还有个可配置的taskDecorator，自己也能实现TaskDecorator定制想要的，后续希望能内置mdc等常用的默认实现

**Comment by magestacks** [comment]
公司使用后，麻烦提交下采用公司，谢谢。

https://hippo4j.cn/users/
