### ISSUE TITLE
[TASK] About CheckStyle Errors

### ISSUE THREAD

**Issue by DDreame** [opengoofy/hippo4j#1229]
There are errors related to CheckStyle. I hope someone can fix them and make pull requests.

  - [ ] hippo4j-threadpool-infra-common @yhc777 
  - [x] hippo4j-threadpool-core @dmego 
  - [x] hippo4j-threadpool-adapter-web
  - [x] hippo4j-threadpool-spring-boot-starter-adapter-web
  - [x] hippo4j-threadpool-config-spring-boot-starter
  - [x] spring-plugin-common
  - [x] hippo4j-threadpool-config-spring-boot-1x-starter
  - [x] spring-boot-1.x-plugin
  - [x] spring-boot-2.x-plugin
  - [x] thread-pool-plugin
  - [x] apollo-plugin
  - [x] hippo4j-agent-bootstrap
  - [x] hippo4j-example-core
  - [x] hippo4j-threadpool-config-nacos-example
  - [x] hippo4j-threadpool-config-apollo-example
  - [x] hippo4j-threadpool-config-zookeeper
  - [x] hippo4j-threadpool-config-consul-example
  - [x] hippo4j-threadpool-config-etcd-example
  - [x] hippo4j-threadpool-config-nacos-spring-boot-1x
  - [x] hippo4j-threadpool-config-apollo-spring-boot-1x-example
  - [x] hippo4j-threadpool-server-spring-boot-starter
  - [x] hippo4j-threadpool-adapter-rabbitmq-example
  - [x] hippo4j-threadpool-adapter-stream-rabbitmq-example
  - [x] hippo4j-threadpool-adapter-stream-rocketmq-example
  - [x] hippo4j-threadpool-adapter-rocketmq-example
  - [x] hippo4j-threadpool-adapter-kafka-example
  - [x] hippo4j-threadpool-server-example
  - [x] hippo4j-threadpool-monitor-elasticsearch-example
  - [x] hippo4j-threadpool-rpc
  - [x] hippo4j-threadpool-server-config
  - [ ] hippo4j-agent-core

If everyone wants to fix those errors, they can change <skip.checkstyle.check>true</skip.checkstyle.check> to false and run mvn package to see more details.

Any pull request related to CheckStyle errors can be associated with this issue, and I will update this document when the PR is merged or find new errors.

**Comment by DDreame** [comment]
I want to fix about module：hippo4j-spring-boot-starter

**Comment by magestacks** [comment]
> I want to fix about module：hippo4j-spring-boot-starter

@DDreame assigned tasks.

**Comment by yhc777** [comment]
I want to fix about module : hippo4j-common

**Comment by Mryanhehe** [comment]
I want to fix module:hippo4j-config-zookeeper-spring-boot-starter-example , but i can't find this module , could you tell me where it's ?

**Comment by magestacks** [comment]
@Mryanhehe Refer to New Package Version.

**Comment by dmego** [comment]
I want to fix about module : hippo4j-threadpool-core, hippo4j-threadpool-rpc

**Comment by magestacks** [comment]
@dmego rpc has been completed, you can change it.
