### ISSUE TITLE
监听RabbitMQ线程池，检测不到。

### ISSUE THREAD

**Issue by z402424668** [opengoofy/hippo4j#1232]
我用的1.5.0版本的Hippo4j-Server。
测试检测三方线程池，测的RabbitMQ线程池。监听不到，不知道具体配置，文档信息就是导入依赖。
我是在自己的服务里追加了adapter依赖，但是看不到信息。
还是说要在Hippo4j-Server端开启三方框架的支持。小懵~~~

**Comment by magestacks** [comment]
把详细步骤列下来。

**Comment by z402424668** [comment]
搞定了亲，发现这里必须要Direct的容器工程。Simple默认的貌似检测不到。
