### ISSUE TITLE
Remove console autofill hippo4j username and password logic

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1246]
## Demand advice

Please answer these questions before submitting them. Thank you.

### Is your function request related to the problem?

NO.

### Describe the function you want

Delete the console to automatically fill in the hippo4j username and password logic based on the domain name.

**Comment by GRL-bxy** [comment]
please assign me

**Comment by magestacks** [comment]
@GRL-bxy Welcome
