### ISSUE TITLE
When the sample program starts, it will initiate two registrations with the Server

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1251]
## BUG Report

Before you start reporting errors, make sure you carefully review the following steps:

- Search for open and closed [GitHub ISSUE](https://github.com/opengoofy/hippo4j/issues)
- Read [Frequently asked questions](https://hippo4j.cn/community/faq)

Please answer these questions before submitting them. Thank you.

### Which Project did you use? Hippo4j config or Hippo4j server?

Hippo4j Server

### Which version did you use?

develop

### Expected behavior

Register only once when the sample program starts.

### Actual behavior

When the sample program starts, it will initiate two registrations with the Server.

<img width="1335" alt="image" src="https://github.com/opengoofy/hippo4j/assets/77398366/63eca26b-dc5d-43d5-97ae-f2bf40ef3b6f">

### Problem recurrence steps

Start hippo4j-server, hippo4j-spring-boot-starter-example in order.

**Comment by wo883721** [comment]
please assign to me.

**Comment by magestacks** [comment]
@wo883721 Welcome
