### ISSUE TITLE
Changed sleep time from 5 seconds to 1 second

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1254]
## Demand advice

Please answer these questions before submitting them. Thank you.

### Describe the function you want

`cn.hippo4j.config.toolkit.SimpleReadWriteLockTest#multiThreadTryWriteLockTest` 

Changed sleep time from 5 seconds to 1 second.

<img width="670" alt="image" src="https://github.com/opengoofy/hippo4j/assets/77398366/564aeb41-6bf2-4b7f-b1a6-5d50f3298c09">

**Comment by tungbq** [comment]
Hi @magestacks May I pick up this task?

**Comment by magestacks** [comment]
@tungbq Welcome, Please resolve the conflict.

**Comment by tungbq** [comment]
@magestacks conflict was resolved, please review again. Thanks!
