### ISSUE TITLE
启动ServerApplication，访问可视化页面，报错403

### ISSUE THREAD

**Issue by Pan-YuJie** [opengoofy/hippo4j#1267]
启动 cn/hippo4j/server/ServerApplication.java
访问不到前端页面

![image-20230514143219405](http://blogqiniuimg.qypanyujie.top/bloglmg/image-20230514143219405.png)

**Comment by magestacks** [comment]
更新最新代码，再试试

**Comment by Pan-YuJie** [comment]
解决了，👍
