### ISSUE TITLE
[Enhancement] FeiShu group chat robot adds signature verification function

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1272]
## Demand advice

Please answer these questions before submitting them. Thank you.

### Is your function request related to the problem?

Yes.

### Describe the function you want

`FeiShu` group chat robot adds signature verification function.

<img width="759" alt="image" src="https://github.com/opengoofy/hippo4j/assets/77398366/f875eef1-4768-470e-9ad8-f8aa36d3cef5">

**Comment by yhc777** [comment]
I want to feature the function! can you assign the issue to me?

**Comment by magestacks** [comment]
@yhc777 welcome

**Comment by magestacks** [comment]
https://github.com/opengoofy/hippo4j/pull/1360
