### ISSUE TITLE
HttpUtilsTest appears extra directory

### ISSUE THREAD

**Issue by pizihao** [opengoofy/hippo4j#1277]
## Demand advice

Please answer these questions before submitting them. Thank you.

### Is your function request related to the problem?

HttpUtilsTest uses the embedded tomcat method to complete the self-test in order to avoid network ip instability during the test, but an additional resource directory will be created after tomcat starts:

<img width="461" alt="dbbbb49978ff4aceb342653a3c99695" src="https://github.com/opengoofy/hippo4j/assets/48643103/81ff8521-a0ab-40b2-8ff6-e5675a302169">

In the previous unit test, the method of deleting the directory after tomcat stopped was set, but due to the different separators of different operating systems, the file could not be deleted successfully on the mac.

### Describe the function you want

Replace the separator, use `File.separator` instead;

![image](https://github.com/opengoofy/hippo4j/assets/48643103/2007dc92-2b86-4b5d-87fd-77e31576e680)

**Comment by lucca-suen** [comment]
Can I try to implement this function?

**Comment by pizihao** [comment]
@lucca-suen  welcome

**Comment by magestacks** [comment]
<img width="467" alt="image" src="https://github.com/opengoofy/hippo4j/assets/77398366/0c8a7336-acaf-48c3-ab5d-e89834c993ca">

problem still exists

**Comment by lucca-suen** [comment]
> <img alt="image" width="467" src="https://user-images.githubusercontent.com/77398366/238838753-0c8a7336-acaf-48c3-ab5d-e89834c993ca.png">
> problem still exists

Does the test class complete the test cycle correctly and completely?
My tests on macOS did not reproduce the phenomenon you describe.

However, if you force termination and force the restart of a new test process when the test class process is not fully completed, you may result in the situation you give.

Perhaps this is not a fault with the code, but rather the result of a wrong use of the test class.

**Comment by magestacks** [comment]
@lucca-suen you are right.

But when executing the packaging process, mistakes are unavoidable.

I think generalization analysis should be done, if there are more than one need to be deleted together.

**Comment by pizihao** [comment]
I haven't found any URLs suitable for HTTP testing, and none of them are stable, so this problem must be solved.

below is my solution: it is not possible to predict where the program will stop when testing, so can we put the tomcat directory in an unimportant directory, such as the test package in the "target" directory:

![image](https://github.com/opengoofy/hippo4j/assets/48643103/a5249f86-0e99-4b85-b766-70a1e3dc86cd)

we usually don't care about what is in this directory, and we will delete this directory with the "clear" and "deploy" of the project.

no weird files even if the program stops under wrong conditions

@lucca-suen @magestacks

**Comment by lucca-suen** [comment]
@pizihao @magestacks 
Based on your opinion, I think it is possible to store the tomcat environment folder in the 'target' directory. 
And in the test class's preprocessor function to clean up the past legacy tomcat environment folder. 
The downside of this is that if the test is interrupted unexpectedly, there will still be an extra folder, but only one at most, which will be cleared the next time the test is performed.

**Comment by lucca-suen** [comment]
@pizihao @magestacks 
Sorry, I just made a mistake and canceled the allocation. 
You can reassign it to me if you think it's okay.
