### ISSUE TITLE
[AGENT] Related Refactoring of the AgentThreadPoolInstanceRegistry Class.

### ISSUE THREAD

**Issue by yanrongzhen** [opengoofy/hippo4j#1296]
## Demand advice
There are two subtasks.
- [ ] Modify the Map field of AgentThreadPoolInstanceRegistry to a static field.
- [ ] Rename the class AgentThreadPoolInstanceRegistry to AgentThreadPoolRegistry for simplicity.

**Comment by lucca-suen** [comment]
Please assign it to me.

**Comment by magestacks** [comment]
@lucca-suen Welcome
