### ISSUE TITLE
Add test case for ClassUtil

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1313]
Code classes that need to develop unit tests:

- `cn.hippo4j.common.toolkit.ClassUtil`

Please refer to the manual for the first contribution: [guide](https://hippo4j.cn/community/contributor-guide)

Unit test development refers to the following two examples:

- `cn.hippo4j.core.executor.DynamicThreadPoolExecutorTest`
- `cn.hippo4j.core.executor.ExtensibleThreadPoolExecutorTest`

**Comment by guanam** [comment]
Hi @magestacks . Can I take that issue?

**Comment by magestacks** [comment]
@guanam Welcome
