### ISSUE TITLE
Add test case for IoUtil

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1326]
Code classes that need to develop unit tests:

- `cn.hippo4j.common.toolkit.IoUtil`

Please refer to the manual for the first contribution: [guide](https://hippo4j.cn/community/contributor-guide)

Unit test development refers to the following two examples:

- `cn.hippo4j.core.executor.DynamicThreadPoolExecutorTest`
- `cn.hippo4j.core.executor.ExtensibleThreadPoolExecutorTest`

**Comment by shuhai65** [comment]
please assign to me.

**Comment by magestacks** [comment]
@shuhai65 Welcome
