### ISSUE TITLE
Add test case for MessageConvert

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1329]
Code classes that need to develop unit tests:

- `cn.hippo4j.common.toolkit.MessageConvert`

Please refer to the manual for the first contribution: [guide](https://hippo4j.cn/community/contributor-guide)

Unit test development refers to the following two examples:

- `cn.hippo4j.core.executor.DynamicThreadPoolExecutorTest`
- `cn.hippo4j.core.executor.ExtensibleThreadPoolExecutorTest`

**Comment by DDreame** [comment]
please assign to me

**Comment by pirme** [comment]
@DDreame Welcome
