### ISSUE TITLE
Add test case for ResizableCapacityLinkedBlockingQueue

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1334]
Code classes that need to develop unit tests:

- `cn.hippo4j.common.executor.support.ResizableCapacityLinkedBlockingQueue`

Please refer to the manual for the first contribution: [guide](https://hippo4j.cn/community/contributor-guide)

Unit test development refers to the following two examples:

- `cn.hippo4j.core.executor.DynamicThreadPoolExecutorTest`
- `cn.hippo4j.core.executor.ExtensibleThreadPoolExecutorTest`

**Comment by Mryanhehe** [comment]
Please assign it to me.

**Comment by magestacks** [comment]
@Mryanhehe Welcome
