### ISSUE TITLE
Dashboard 线程池实例列表 Active头展示错误

### ISSUE THREAD

**Issue by Jamel-jun** [opengoofy/hippo4j#1369]
如题，这个Active表头是指的详情中的环境标识么还是运行状态
![image](https://github.com/opengoofy/hippo4j/assets/50609931/816c60c5-3875-4a92-8d10-7e5fdb13e41d)
![image](https://github.com/opengoofy/hippo4j/assets/50609931/85508c06-7ff5-4ca3-93f5-64e0c5df92ff)

**Comment by zjHe** [comment]
环境标识
