### ISSUE TITLE
[Enhancement] Added Undertow thread pool parameters

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1375]
## Demand advice

Please answer these questions before submitting them. Thank you.

### Describe the function you want

If you encounter a parameter that cannot be provided, provide an explanation of the reason.

<img width="1714" alt="image" src="https://github.com/opengoofy/hippo4j/assets/77398366/8c4f2da4-65fd-4353-9b7a-46e5545bae19">

<img width="1033" alt="image" src="https://github.com/opengoofy/hippo4j/assets/77398366/ed5e9944-bbfa-4a4c-8639-457eaa5dee24">

**Comment by furaul** [comment]
please assign to me

**Comment by magestacks** [comment]
@furaul welcome
