### ISSUE TITLE
Creating a thread pool block queue cannot change the content of the drop-down box

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1390]
The content of the drop-down box cannot be changed after the selection.

<img width="1683" alt="image" src="https://github.com/opengoofy/hippo4j/assets/77398366/d5df2376-32ae-4703-a229-f6fed092897a">

**Comment by GRL-bxy** [comment]
please assign me

**Comment by GRL-bxy** [comment]
It has been changed and can be submitted directly
