### ISSUE TITLE
线程池适配器采集报空指针

### ISSUE THREAD

**Issue by zjHe** [opengoofy/hippo4j#1393]
### Which Project did you use? Hippo4j config or Hippo4j server?
server 
### Which version did you use?
1.5.0
### Expected behavior

不报错

### Actual behavior

![image](https://github.com/opengoofy/hippo4j/assets/34431616/68dd2582-3f69-4ad7-a322-7bfc747ba6fc)

### Cause analysis (if possible)

监控采集了这个参数，但是这个参数并没有在适配器中set入，所以值为null，在采集转换double的时候异常。

![image](https://github.com/opengoofy/hippo4j/assets/34431616/0d97214b-0db6-4a46-837b-7b4c88485e8b)

![image](https://github.com/opengoofy/hippo4j/assets/34431616/b3abfd0f-0e3e-4cfe-a1eb-e3d58effaeaa)

![image](https://github.com/opengoofy/hippo4j/assets/34431616/cd935fbe-b9c2-4547-aab9-89b3cffbb724)

**Comment by Createsequence** [comment]
有兴趣提个 PR 修复一下吗？
