### ISSUE TITLE
Add test case for ServiceException

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1397]
Code classes that need to develop unit tests:

- `cn.hippo4j.server.common.base.exception.ServiceException`

Please refer to the manual for the first contribution: [guide](https://hippo4j.cn/community/contributor-guide)

Unit test development refers to the following two examples:

- `cn.hippo4j.core.executor.DynamicThreadPoolExecutorTest`
- `cn.hippo4j.core.executor.ExtensibleThreadPoolExecutorTest`

**Comment by Han-Xinlong** [comment]
Please assign it to me.

**Comment by magestacks** [comment]
@Han-Xinlong Welcome
