### ISSUE TITLE
将用于收集线程池信息的缓冲线程池从ArrayBlockingQueue替换为LinkedBlockingQueue类型

### ISSUE THREAD

**Issue by LukeLiang** [opengoofy/hippo4j#1404]
## Demand advice

Please answer these questions before submitting them. Thank you.

### Is your function request related to the problem?
将用于收集线程池信息的缓冲线程池从ArrayBlockingQueue替换为LinkedBlockingQueue类型。
原因：
1. LinkedBlockingQueue没有容量限制，可以根据需要动态增加队列大小
2. LinkedBlockingQueue在生产者和消费者之间使用两个锁(分别是一个putLock和一个takeLock)，能够增加并发处理的能力

所以，LinkedBlockingQueue更适合高并发下生产者和消费者模式。

### Describe the function you want
代码位置：ReportingEventExecutor.java
创建 messageCollectVessel 时, 修改为LinkedBlockingQueue类型
![issue](https://github.com/opengoofy/hippo4j/assets/39796629/38c20762-243e-4872-8065-2b3082a2bd53)

**Comment by magestacks** [comment]
@LukeLiang Welcome

**Comment by LukeLiang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
