### ISSUE TITLE
使用hippo4j server   控制台无法看到线程池实例

### ISSUE THREAD

**Issue by raven1997s** [opengoofy/hippo4j#1418]
## Question

Before you begin to report problems, make sure you carefully review the following steps:

- Searches for open and closed [GitHub ISSUE](https://github.com/opengoofy/hippo4j/issues)
- Read [Frequently asked questions](https://hippo4j.cn/community/faq)

Please answer these questions before submitting them. Thank you.

### Which Project did you use? Hippo4j config or Hippo4j server?
Hippo4j server 

### Which version did you use?
id("org.springframework.boot") version "2.7.14"
jdk 1.8
### Expected behavior
![image](https://github.com/opengoofy/hippo4j/assets/52941626/7e43bd87-fa4e-473b-b799-3e33980cdfc0)

控制台可以看到线程池实例 动态修改
### Actual behavior
看不到线程池实例
### Problem recurrence steps
按照官方文档进行操作，无特殊操作
### Sample code to reproduce the problem (for example, the GitHub Link) 
https://github.com/raven1997s/coding-life/tree/main/hippo4j-server-demo

**Comment by magestacks** [comment]
依赖 Jar 为 Config 模式，尝试切换 Server 模式。
