### ISSUE TITLE
[Enhancement] Check the required fields such as the configuration center when the Config mode starts

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1439]
### Search before asking

- [X] I had searched in the [issues](https://github.com/opengoofy/hippo4j/issues) and found no similar issues.

### Enhancement Request

Check the required fields such as the configuration center when the Config mode starts.

- [x] Nacos @2084276225  https://github.com/opengoofy/hippo4j/pull/1438
- [x] Zookeeper @xjlgod https://github.com/opengoofy/hippo4j/pull/1457
- [x] Apollo @Myboolean https://github.com/opengoofy/hippo4j/pull/1452
- [x] ETCD @liguangling-lgl https://github.com/opengoofy/hippo4j/pull/1440
- [x] Polaris @mazengrun  https://github.com/opengoofy/hippo4j/pull/1470
- [ ] Consul

### Describe the solution you'd like

`BeforeCheckConfiguration` for validation.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by 2084276225** [comment]
Please assign me the Nacos configuration

**Comment by magestacks** [comment]
@2084276225 Welcome

**Comment by liguangling-lgl** [comment]
Please assign me the Nacos configuration

**Comment by liguangling-lgl** [comment]
Please assign me the ETCD configuration

**Comment by magestacks** [comment]
@liguangling-lgl Welcome

**Comment by Myboolean** [comment]
Please assign me the  Apollo configuration

**Comment by magestacks** [comment]
@Myboolean Welcome

**Comment by xjlgod** [comment]
Please assign me the Zookeeper configuration

**Comment by magestacks** [comment]
@xjlgod Welcome

**Comment by mazengrun** [comment]
Please assign me the Polaris configuration

**Comment by magestacks** [comment]
@mazengrun Welcome

**Comment by dyx1234** [comment]
It's been a few months, can you assign consul to me now
