### ISSUE TITLE
 Under the develop branch, start the project, and the user rights module clicks the Add button directly without loading the tenant data

### ISSUE THREAD

**Issue by 2084276225** [opengoofy/hippo4j#1443]
### Search before asking

- [X] I had searched in the [issues](https://github.com/opengoofy/hippo4j/issues) and found no similar issues.

### Environment

Windows

### Hippo4j version

develop

### What happened

<img width="954" alt="1693728706863" src="https://github.com/opengoofy/hippo4j/assets/45718103/01aed7d5-0edb-40ad-8678-dc84fb3860e0">
<img width="1005" alt="1693728706825" src="https://github.com/opengoofy/hippo4j/assets/45718103/9051dece-3b0d-458d-be91-bc2b69542e79">

### How to reproduce

<img width="954" alt="1693728706863" src="https://github.com/opengoofy/hippo4j/assets/45718103/759ac008-f58b-48e2-a7ef-f5036cc65c2a">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by dmego** [comment]
plz assign to me

**Comment by magestacks** [comment]
@dmego Welcome
