### ISSUE TITLE
[Question] 是否支持自动扩展线程池中的线程数

### ISSUE THREAD

**Issue by qianchonghao** [opengoofy/hippo4j#1497]
### Search before asking

- [X] I had searched in the [issues](https://github.com/opengoofy/hippo4j/issues) and found no similar issues.

### Question

1. 在监控模块收集线程池指标（如在两周维度的活跃度、拒绝异常、LargestPoolSize、）。
2. 利用以上指标，设置阈值。**触发阈值（上限则【一定范围内】自动扩容maxPoolSize，下限则推送消息提示冗余）**
我的问题是：这种根据监控指标自动扩缩线程池配置的特性，是否支持。如果不支持，请问是这种做法会有对应的隐患吗？

**Comment by weihubeats** [comment]
不支持，实际线上线程池的配置本身就没有一个特别的标准，需要实际根据机器和应用进行压测调试才能选用一个最合适的参数。现在云环境下更多的是基于k8s的扩容策略去自动扩容pod而不是自动调整线程池，本身机器的性能瓶颈并不能靠扩容线程池去解决问题。
