### ISSUE TITLE
项目删除成功，弹窗提示信息错误(小问题)

### ISSUE THREAD

**Issue by caizhenboy** [opengoofy/hippo4j#1522]
### Search before asking

- [X] I had searched in the [issues](https://github.com/opengoofy/hippo4j/issues) and found no similar issues.

### Environment

Windows

### Hippo4j version

1.5.0

### What happened

删除成功，但是提示“创建成功”，是个小问题，但是希望hippo4j更完美
![1](https://github.com/opengoofy/hippo4j/assets/37531844/a2f0e989-49ac-4c08-8e82-31cfce8f71a0)

### How to reproduce

you know

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by fFee-ops** [comment]
这个管理后台的账号密码是多少呀？文档中写的好像是错的

**Comment by zhengkezhou1** [comment]
hi @magestacks, i want to try this

**Comment by magestacks** [comment]
@zzzk1 Welcome

**Comment by fengluo97** [comment]
@magestacks hi, may I try this as well? This will be my first attempt on github.

**Comment by paradiseidler** [comment]
This issue hasn’t been resolved for a year; could I give it a try?  @magestacks
