### ISSUE TITLE
是否支持通过动态设置id来控制线程大小

### ISSUE THREAD

**Issue by pipti** [opengoofy/hippo4j#1524]
### Search before asking

- [X] I had searched in the [issues](https://github.com/opengoofy/hippo4j/issues) and found no similar issues.

### Feature Request

是否支持通过动态设置id来控制线程大小，比如对每个用户的线程池进行大小控制

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by magestacks** [comment]
Dynamic parameter expansion is not supported. Parameters can be modified through openapi control.
