### ISSUE TITLE
[Bug] Cannot determine local hostname

### ISSUE THREAD

**Issue by YeLuoXu** [opengoofy/hippo4j#1534]
### Search before asking

- [X] I had searched in the [issues](https://github.com/opengoofy/hippo4j/issues) and found no similar issues.

### Environment

Mac

### Hippo4j version

1.5.0

### What happened

持续出现INFO日志
 c.h.core.toolkit.inet.InetUtils [convertAddress:155]: - Cannot determine local hostname

### How to reproduce

server端：动态线程池 -> 线程池实例 ，点击查看详情
<img width="1412" alt="image" src="https://github.com/opengoofy/hippo4j/assets/38717689/d536f903-2ef4-40d8-a9d8-853e812df5d4">

### Debug logs

2024-03-13 15:35:44.753 [TID: N/A] INFO  [nio-8002-exec-6] c.h.core.toolkit.inet.InetUtils [convertAddress:155]: - Cannot determine local hostname

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by magestacks** [comment]
无法复现该问题，Debug 看下为什么会出现这个呢
