### ISSUE TITLE
[Question] Question title 为什么我在后台修改线程池参数之后必须重启spring boot项目才会生效？否则参数还是更新之前的？是哪里有缓存吗？

### ISSUE THREAD

**Issue by dieselzpzhong** [opengoofy/hippo4j#1568]
### Search before asking

- [X] I had searched in the [issues](https://github.com/opengoofy/hippo4j/issues) and found no similar issues.

### Question

如题：我在后台修改线程池参数之后必须重启spring boot项目才会生效？否则参数还是更新之前的？是哪里有缓存吗？

**Comment by paradiseidler** [comment]
@dieselzpzhong  ![111](https://github.com/user-attachments/assets/e4915eb8-5fdf-46c4-a4c7-c725535bc967)

**Comment by magestacks** [comment]
> @dieselzpzhong ![111](https://private-user-images.githubusercontent.com/125356788/384321284-e4915eb8-5fdf-46c4-a4c7-c725535bc967.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzA4MDEsIm5iZiI6MTczMTA3MDUwMSwicGF0aCI6Ii8xMjUzNTY3ODgvMzg0MzIxMjg0LWU0OTE1ZWI4LTVmZGYtNDZjNC1hNGM3LWM3MjU1MzViYzk2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxMjU1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWQ3NmI2MzE3ZTgyMTM2ZjI2MzIyNTgzZDkyZmQ4YjNkZDE3ODM3NTcxMzU2YTMzYjQ4YTNlMTQ1Y2I4ODk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.x-sQiTd7Tw0hrUHHuNGmkOA_NnLuHBHQSPS_xBkmy-k)

👍
