### ISSUE TITLE
优化报警过滤逻辑

### ISSUE THREAD

**Issue by mabaiwan** [opengoofy/hippo4j#176]
目前配置线程池报警过滤规则：线程池下某一报警类型在指定时间内仅出现一次；

需要修改为：线程池下某一报警类型在指定时间内出现指定次数后拦截过滤。

**Comment by hl1248** [comment]
我来+1111

**Comment by mabaiwan** [comment]
@hl1248 这一块暂时还没想好要如何优化，如果你有想法可以说下哈

**Comment by hl1248** [comment]
可以用队列存储的是每一次报警的时间戳，Map<String, Cache<String, List<Long>>>(线程池标识，报警类型，队列)，队列size达到限制次数，则获取队列中最早添加的时间戳。这样可以吗

**Comment by hl1248** [comment]
> @hl1248 这一块暂时还没想好要如何优化，如果你有想法可以说下哈

类似滑动窗口

**Comment by mabaiwan** [comment]
@hl1248 周末我会重构报警通知模块 https://github.com/opengoofy/hippo4j/issues/360，过程中我也想想，有结果在 Issue 留言回复哈

**Comment by mabaiwan** [comment]
暂时不做优化，没有很好的业务场景，后面想到后再打开该 Issue
