### ISSUE TITLE
用户登录时候，如果输入了不存在的用户名，后台报空指针异常

### ISSUE THREAD

**Issue by linlinjie** [opengoofy/hippo4j#272]
### 你使用了哪个项目？Hippo-4J Server 还是 Hippo-4J Core?
Hippo-4J Server
### 你使用了哪个版本？
1.3.0
### 实际行为
后台报空指针异常
### 原因分析（如果可以）
cn.hippo4j.auth.service.impl.UserDetailsServiceImpl#loadUserByUsername 方法
userMapper获取用户信息，没有对用户信息判空
### 问题重现步骤
输入一个不存在的用户名即可重现
### 用于重现此问题的示例代码
https://github.com/mabaiwan/hippo4j/blob/develop/hippo4j-auth/src/main/java/cn/hippo4j/auth/service/impl/UserDetailsServiceImpl.java

**Comment by mabaiwan** [comment]
@linlinjie 有兴趣帮忙尝试修复这个问题么

**Comment by linlinjie** [comment]
有啊，马兄莫急，我最近也比较忙，等待我提MR
