### ISSUE TITLE
hippo4j Banner GitHub 网址信息修改

### ISSUE THREAD

**Issue by yin-huahua** [opengoofy/hippo4j#351]
`DynamicThreadPoolBannerHandler` 中 HIPPO4J_GITHUB 变量修改：

Before：
GitHub:  https://github.com/mabaiwan/hippo4j

After：
GitHub:  https://github.com/opengoofy/hippo4j

**Comment by shanjianq** [comment]
i can do this

**Comment by mabaiwan** [comment]
@yin-huahua 欢迎
