### ISSUE TITLE
hippo4j 官网修改底部加群链接

### ISSUE THREAD

**Issue by mabaiwan** [opengoofy/hippo4j#369]
![image](https://user-images.githubusercontent.com/77398366/180591915-ce166a45-3bd4-4528-9100-147778a6fe48.png)

修改为：https://hippo4j.cn/docs/user_docs/other/group

**Comment by wzw8795** [comment]
ma ge ,wo xiang zuo zhe ge

**Comment by yin-huahua** [comment]
@wzw8795 欢迎
