### ISSUE TITLE
客户端健康检查时间顺延机制

### ISSUE THREAD

**Issue by pirme** [opengoofy/hippo4j#439]
目前客户端检查服务端是否可用，使用定时任务 5s 执行一次。如果服务端停机，依然 5s 执行一次，可以对此进行优化：

`HttpScheduledHealthCheck#sendHealthCheck` 方法进行检查失败时，检查时间顺延。顺延逻辑：第一次失败 5s，第二次失败 5s，第三次失败 10s，第四次及以上失败 30s。

**Comment by linlinjie** [comment]
come on

**Comment by linlinjie** [comment]
/**
     * Health check.
     */
    public void healthCheck() {
        boolean healthCheckStatus = sendHealthCheck();
        if (healthCheckStatus) {
            if (Objects.equals(healthStatus, false)) {
                healthStatus = true;
                checkFailureCount = 0;
                log.info("The client reconnects to the server successfully.");
                signalAllBizThread();
            }
        } else {
            healthStatus = false;
            checkFailureCount++;
            log.error("health check fail times since last successful:{}", checkFailureCount);
            try {
                if (checkFailureCount == 1) {
                    return;
                } else if (checkFailureCount > 1 && checkFailureCount < 4) {
                    Thread.sleep(HEALTH_CHECK_INTERVAL * 1000 * (checkFailureCount - 1));
                } else {
                    Thread.sleep(25000L);
                }
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
