### ISSUE TITLE
MyBatisPlus 修改全局填充方法优化

### ISSUE THREAD

**Issue by Hibernate5666** [opengoofy/hippo4j#501]
hippo4j-config模块
mybatisPlus配置有点问题
![image](https://user-images.githubusercontent.com/30147527/183383100-fcac1daa-68bd-404f-9f2e-62680bdbb9e6.png)
更新字段应该用strictUpdateFill吧

**Comment by pirme** [comment]
@Hibernate5666 目前这么写是可以完成效果的。如果你觉得语义不对，可以本地测试后，提个 PR。

**Comment by Hibernate5666** [comment]
> @Hibernate5666 目前这么写是可以完成效果的。如果你觉得语义不对，可以本地测试后，提个 PR。

好的
