### ISSUE TITLE
rabbitmq模块设计问题

### ISSUE THREAD

**Issue by ChengHoHang** [opengoofy/hippo4j#533]
## 问题支持

大佬你好，关于rabbitmq-adapter模块设计有点不解，为什么只对1个mq数据源做动态修改？

![image](https://user-images.githubusercontent.com/48877754/185027290-93956059-9ffb-4284-9ce3-55c36a1bd7d2.png)

![image](https://user-images.githubusercontent.com/48877754/185027337-547a6b88-bf3c-415e-af24-9aae9fe1603c.png)

### 你使用了哪个版本？

v1.4

### 预期行为

应该是参考其他模块那样，直接扫描spring容器下的所有ConnectionFactory，实际项目可能会有多个mq数据源

### 实际行为

未启动过项目，但从代码上看，只autowired一个ConnectionFactory，即只能对其中一个mq数据源动态修改线程池配置

### 原因分析（如果可以）

如预期行为所示

### 用于重现此问题的示例代码（例如 GitHub 链接）

是代码实现问题，还是我看漏了，望大佬解答，respect

**Comment by weihubeats** [comment]
这里当初设计的时候没有考虑到多RabbitMQ源的问题，可以在后续版本优化

**Comment by pirme** [comment]
@ChengHoHang 优化了 rabbotMQ 实现，可以再看下

**Comment by ChengHoHang** [comment]
Thanks for contributing
