### ISSUE TITLE
提供 ExecutorContext 封装上下文细节

### ISSUE THREAD

**Issue by pirme** [opengoofy/hippo4j#555]

**Comment by pirme** [comment]
当线程池存在超时报警时，可以通过以下方式将链路信息放入报警信息中。

MDC.put(EXECUTE_TIMEOUT_TRACE, executeTimeoutTrace);

创建 ExecutorContext 类，提供 putExecuteTimeoutTrace 方法，屏蔽 EXECUTE_TIMEOUT_TRACE 常量。

**Comment by road2master** [comment]
I can do this task
