### ISSUE TITLE
创建 Issue 模板内容变更

### ISSUE THREAD

**Issue by pirme** [opengoofy/hippo4j#571]
修改 Hippo-4J Core 为 Hippo-4J Config

涉及文件：

- https://github.com/opengoofy/hippo4j/tree/develop/.github/ISSUE_TEMPLATE

**Comment by soulmz** [comment]
试试

**Comment by wangyi123456** [comment]
我我我 也想试试

**Comment by pirme** [comment]
@soulmz https://github.com/opengoofy/hippo4j/issues/574 已分配，可以关注下其它进阶 issue https://github.com/opengoofy/hippo4j/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+pro+issue%22

**Comment by pirme** [comment]
@wangyi123456 欢迎，可以直接在 github 完成操作。

如果想在 idea 中变更提交，请注意邮箱配置，https://hippo4j.cn/docs/community/contributor
