### ISSUE TITLE
修改官网配置文件 receive 命名错误

### ISSUE THREAD

**Issue by pirme** [opengoofy/hippo4j#574]
receive 修改为 receives

https://github.com/opengoofy/hippo4j/blob/develop/docs/docs/user_docs/getting-started/hippo4j-core-start.md

**Comment by soulmz** [comment]
我试试。

**Comment by pirme** [comment]
@soulmz 欢迎，可以直接在 github 完成操作。

如果想在 idea 中变更提交，请注意邮箱配置，https://hippo4j.cn/docs/community/contributor
