### ISSUE TITLE
BooleanUtilTest 补充测试用例

### ISSUE THREAD

**Issue by agentart** [opengoofy/hippo4j#581]
参考 `cn.hippo4j.common.toolkit.ArrayUtilTest#assertIsEmpty` 完成 BooleanUtilTest 其余单元测试。

> 初次提交注意本地 git 配置，[贡献指南](https://hippo4j.cn/docs/community/contributor)

**Comment by wangjie-github** [comment]
小马哥，我来认领😀

**Comment by agentart** [comment]
@wangjie-github 已分配，欢迎 👏
