### ISSUE TITLE
ByteConvertUtilTest 补充测试用例

### ISSUE THREAD

**Issue by agentart** [opengoofy/hippo4j#582]
参考 `cn.hippo4j.common.toolkit.ArrayUtilTest#assertIsEmpty` 完成 ByteConvertUtilTest 其余单元测试。

> 初次提交注意本地 git 配置，[贡献指南](https://hippo4j.cn/docs/community/contributor)

**Comment by onesimplecoder** [comment]
认领

**Comment by agentart** [comment]
@onesimplecoder 已分配，欢迎 👏

**Comment by agentart** [comment]
done
