### ISSUE TITLE
ContentUtilTest 补充测试用例

### ISSUE THREAD

**Issue by itmachen** [opengoofy/hippo4j#586]
参考 `cn.hippo4j.common.toolkit.ArrayUtilTest#assertIsEmpty` 完成 ContentUtilTest 其余单元测试。

> 初次提交注意本地 git 配置，[贡献指南](https://hippo4j.cn/docs/community/contributor)

**Comment by liulinfei121** [comment]
认领

**Comment by agentart** [comment]
@liulinfei121 欢迎，首次贡献请参考 [贡献指南](https://hippo4j.cn/docs/community/contributor)

**Comment by agentart** [comment]
@liulinfei121 请问有在进行开发么

**Comment by liulinfei121** [comment]
不好意思，上周有其他事，这两天开发

**Comment by itmachen** [comment]
done
