### ISSUE TITLE
修改官网三方框架线程池中 hippo4j 命名

### ISSUE THREAD

**Issue by agentart** [opengoofy/hippo4j#596]
修改页面中 Hippo4J Core 为 Hippo4J Config

https://github.com/opengoofy/hippo4j/blob/develop/docs/docs/user_docs/getting-started/hippo4j-adapter.md

**Comment by agentart** [comment]
done

**Comment by hbw1994** [comment]
这个我认领了

**Comment by agentart** [comment]
@hbw1994 欢迎，首次贡献请参考 [贡献指南](https://hippo4j.cn/docs/community/contributor)

**Comment by agentart** [comment]
@hbw1994 请问这个任务有在进行么

**Comment by hbw1994** [comment]
周六能有时间弄，这两天公司太忙，没抽出时间弄，不好意思

**Comment by hbw1994** [comment]
> @hbw1994 请问这个任务有在进行么
周六能有时间弄，这两天公司太忙，没抽出时间弄，不好意思

**Comment by hbw1994** [comment]
> Hippo4J Core 为 Hippo4J Config

你好，这个任务已经修改完毕
