### ISSUE TITLE
全局移除 Guava 工具包依赖

### ISSUE THREAD

**Issue by itmachen** [opengoofy/hippo4j#598]
避免客户端引用 hippo4j 与本地 guava 版本冲突，特此移除 guava 版本依赖。

**Comment by xiaochengxuyuan** [comment]
我试试~

**Comment by road2master** [comment]
I can do this task

**Comment by agentart** [comment]
@road2master 不好意思大佬 @xiaochengxuyuan 先来的哈

@xiaochengxuyuan 正式开始前，可以先梳理下目前 guava 的用途和替换思路。在这个 issue 下评论就好

**Comment by agentart** [comment]
@road2master 正式开始前，可以先梳理下目前 guava 的用途和替换思路。在这个 issue 下评论就好

**Comment by road2master** [comment]
> @road2master 正式开始前，可以先梳理下目前 guava 的用途和替换思路。在这个 issue 下评论就好

 @agentart 刚没看到，哈哈。 @xiaochengxuyuan 大佬要不你来，小弟观摩就好

**Comment by pirme** [comment]
我看是 @xiaochengxuyuan 大佬自己删除了留言，不知道是什么原因

**Comment by xiaochengxuyuan** [comment]
> 我看是 @xiaochengxuyuan 大佬自己删除了留言，不知道是什么原因

嗯……  怂一波怂一波，让 @road2master  来吧~~
