### ISSUE TITLE
Dependency optimization

### ISSUE THREAD

**Issue by weihubeats** [opengoofy/hippo4j#599]
## 需求建议

请在提交问题之前回答这些问题，谢谢。

### 您的功能请求是否与问题有关？
no
### 描述你想要的功能
At present, some pom dependency management of the project is very messy, whether to consider optimization, for example, some modules do not need to define their own version separately, and use the parent version uniformly

**Comment by agentart** [comment]
@weihubeats can you give some examples?

**Comment by weihubeats** [comment]
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/42484192/187054636-ec9114d8-3709-42e5-878c-4142ef804542.png">
<img width="476" alt="image" src="https://user-images.githubusercontent.com/42484192/187054673-8ff9a279-55bb-49e0-8ea7-d36ea87150c8.png">
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/42484192/187054680-f3cb7b01-616a-4d42-9210-be5614989e94.png">
This can be unified in the maven parent module definition, sub-modules do not need to specify the version

**Comment by agentart** [comment]
The version number that is not reused, I don't think it is necessary to put it in the root pom

**Comment by weihubeats** [comment]
I understand that because the root directory has already managed the spring version uniformly, the spring version does not need to be formulated, unless a different spring version is to be used here

**Comment by agentart** [comment]
Potential hidden dangers scanned by security software, normally do not need to be specified

**Comment by weihubeats** [comment]
I see
