### ISSUE TITLE
Server 端新增是否认证模式

### ISSUE THREAD

**Issue by itmachen** [opengoofy/hippo4j#60]
Hippo4J 服务端请求默认需要鉴权，新增鉴权开关功能

**Comment by baymax55** [comment]
请问该开关开启后,客户端和管理后台都不需要进行token校验,还是说只是客户端不需要校验而管理后台的访问需要校验

**Comment by pirme** [comment]
我觉得大概分为 2 个点：

- [ ] 客户端不需要再配置用户名、密码。
- [ ] 服务端不再需要进行用户名、密码。

**Comment by pirme** [comment]
我觉得大概分为 2 个点：

- 客户端不需要再配置用户名、密码。
- 服务端不再需要进行用户名、密码。

**Comment by baymax55** [comment]
assign to me

**Comment by pirme** [comment]
@baymax55 欢迎
