### ISSUE TITLE
ByteConvertUtil#getPrintSize单位转换错误

### ISSUE THREAD

**Issue by onesimplecoder** [opengoofy/hippo4j#601]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/docs/user_docs/other/issue)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?
hippo4j config
### 你使用了哪个版本？
1.4.1
### 预期行为
cn.hippo4j.common.toolkit.ByteConvertUtil#getPrintSize转换单位  ByteConvertUtil.getPrintSize(2200000000L)=2.04G         
### 实际行为
2.4G
### 原因分析（如果可以）
转换成GB时，小数部分为个位数直接拼接，导致2.04G成为2.4G。转换为MB时，由于long一直为小数整数，小数部分无论何种情况都不会有值
        `if (size < covertNum) {
            size = size * 100;
            return (size / 100) + "." + (size % 100) + "MB";
        } else {
            size = size * 100 / covertNum;
            return (size / 100) + "." + (size % 100) + "GB";
        }` 
### 问题重现步骤
如上
### 用于重现此问题的示例代码（例如 GitHub 链接）
无

**Comment by agentart** [comment]
@onesimplecoder 可以提交个 pr 修复下么

**Comment by onesimplecoder** [comment]
好的

**Comment by agentart** [comment]
请注意邮箱设置，参考 [贡献者指南](https://hippo4j.cn/docs/community/contributor)
