### ISSUE TITLE
Undertow 获取 WebServer 类型参数异常

### ISSUE THREAD

**Issue by mfandcc** [opengoofy/hippo4j#608]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/docs/user_docs/other/issue)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?
hippo4j server
### 你使用了哪个版本？
1.4.0
### 预期行为
监控和管理Undertow
### 实际行为
获取信息失败
### 原因分析（如果可以）
- Spring Boot WebApplicationType为servlet时，UndertowWebThreadPoolHandler#getWebThreadPoolByServer方法获取到的WebServer参数类型是UndertowServletWebServer，导致转换UndertowWebServer类型失败
- 因转换失败，UndertowWebThreadPoolHandler#simpleInfo方法中，executor参数null，空指针异常

**Comment by pirme** [comment]
@mfandcc 感谢反馈，这个问题会在 1.4.1 版本解决

**Comment by agentart** [comment]
@mfandcc 请问 springboot 版本是多少，另外有无自定义 Undertow 版本

**Comment by mfandcc** [comment]
> @mfandcc 请问 springboot 版本是多少，另外有无自定义 Undertow 版本

springboot 2.2.5，未对Undertow版本，配置修改

**Comment by agentart** [comment]
收到

**Comment by pirme** [comment]
@mfandcc 问题已修复，请根据 hippo4j 最新版本进行验证
