### ISSUE TITLE
FastJSON 序列化替换为 JSONUtil

### ISSUE THREAD

**Issue by shanjianq** [opengoofy/hippo4j#613]
发现现在代码中fastJson的版本号不一致且部分版本过低。发布到生产环境存在漏洞扫描不通过的风险，所以可否统一升级到对应的安全版本。

**Comment by pirme** [comment]
hippo4j 中并没有 fastjson 的依赖，可能存在测试代码引用。可以尝试删除 fastjson 依赖，并使用 hippo4j 内部 JSONUtil 替换。

**Comment by shanjianq** [comment]
查询了一下的确是在example中存在引用，那么对实际使用中不会引入fastjson。

**Comment by pirme** [comment]
@shanjianq 可以尝试删除 fastjson 依赖，并使用 hippo4j 内部 JSONUtil 替换下

**Comment by shanjianq** [comment]
get it，周末有空弄下
