### ISSUE TITLE
动态线程池设置关闭时启动报错

### ISSUE THREAD

**Issue by dousp** [opengoofy/hippo4j#617]
## BUG 报告

- hippo4j server 1.4.0
- 启动失败
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method threadPoolRunStateHandler in cn.hippo4j.springboot.starter.adapter.web.WebAdapterAutoConfiguration required a bean of type 'cn.hippo4j.core.toolkit.inet.InetUtils' that could not be found.


Action:

Consider defining a bean of type 'cn.hippo4j.core.toolkit.inet.InetUtils' in your configuration.
```

### 原因分析（如果可以）

推测大概是自动装配逻辑那

### 问题重现步骤
```
spring:
  dynamic:
      enable: false
```

**Comment by pirme** [comment]
@dousp 感谢反馈，会在 1.4.1 版本解决。如果您有兴趣也可以尝试进行解决并提交 PR 修复

**Comment by dousp** [comment]
#### 我看了下代码：
- **hippo4j-spring-boot-starter**中的`DynamicThreadPoolAutoConfiguration`中注入的 `InetUtils`
- **hippo4j-spring-boot-starter**中引入了**hippo4j-spring-boot-starter-adapter-web**依赖
- **hippo4j-spring-boot-starter-adapter-web**也是遵循自动装配的，而不是受到**hippo4j-spring-boot-starter**的管理
- 基于这种方式，`WebAdapterAutoConfiguration`没有像`DynamicThreadPoolAutoConfiguration`那样有特定的装配条件，所以启动的时候出现了上述问题

#### 我觉得两种解决方式吧：
##### 一种是：
- 直接在`WebAdapterAutoConfiguration`中加上`DynamicThreadPoolAutoConfiguration`的`@ConditionalOnProperty(prefix = “spring.dynamic.thread-pool”, value = "enable", matchIfMissing = true, havingValue = "true")`条件即可
##### 另一种是：
- **hippo4j-spring-boot-starter-adapter-web**改为不是自动装配，然后在**hippo4j-spring-boot-starter**中根据条件转配即可

#### 采用哪种方式呢，还是有别的更好的方式？

**Comment by agentart** [comment]
@dousp 推荐第一种哈

**Comment by agentart** [comment]
@dousp 还是推荐第二种吧
