### ISSUE TITLE
修改 DynamicThreadPoolCoreAutoConfiguration 为 DynamicThreadPoolAutoConfiguration

### ISSUE THREAD

**Issue by pirme** [opengoofy/hippo4j#632]
设计修改文件：

- hippo4j-spring-boot/hippo4j-config-spring-boot-starter/src/main/resources/META-INF/spring.factories
- cn.hippo4j.config.springboot.starter.config.DynamicThreadPoolCoreAutoConfiguration

**Comment by op-lht** [comment]
认领
