### ISSUE TITLE
Md5UtilTest 补充测试用例

### ISSUE THREAD

**Issue by itmachen** [opengoofy/hippo4j#640]
参考 `cn.hippo4j.common.toolkit.ArrayUtilTest#assertIsEmpty` 完成该单元测试任务。

> 初次提交注意本地 git 配置，参考 [贡献指南](https://hippo4j.cn/docs/community/contributor)

**Comment by liulinfei121** [comment]
认领

**Comment by pirme** [comment]
@liulinfei121 欢迎 👏

**Comment by liulinfei121** [comment]
#640 已完成

**Comment by itmachen** [comment]
done
