### ISSUE TITLE
SingletonTest 补充测试用例

### ISSUE THREAD

**Issue by itmachen** [opengoofy/hippo4j#642]
参考 `cn.hippo4j.common.toolkit.ArrayUtilTest#assertIsEmpty` 完成该单元测试任务。

> 初次提交注意本地 git 配置，参考 [贡献指南](https://hippo4j.cn/docs/community/contributor)

**Comment by liulinfei121** [comment]
认领

**Comment by agentart** [comment]
@liulinfei121 欢迎 👏

**Comment by pirme** [comment]
@liulinfei121 hello，任务还在进行么

**Comment by liulinfei121** [comment]
在，明天提交
