### ISSUE TITLE
StringUtilTest 补充测试用例

### ISSUE THREAD

**Issue by agentart** [opengoofy/hippo4j#643]
参考 `cn.hippo4j.common.toolkit.ArrayUtilTest#assertIsEmpty` 完成该单元测试任务。

> 初次提交注意本地 git 配置，参考 [贡献指南](https://hippo4j.cn/docs/community/contributor)

**Comment by Tliutao** [comment]
我来

**Comment by Tliutao** [comment]
我来

**Comment by pirme** [comment]
@Tliutao 欢迎
