### ISSUE TITLE
UserContextTest 补充测试用例

### ISSUE THREAD

**Issue by agentart** [opengoofy/hippo4j#645]
参考 `cn.hippo4j.common.toolkit.ArrayUtilTest#assertIsEmpty` 完成该单元测试任务。

> 初次提交注意本地 git 配置，参考 [贡献指南](https://hippo4j.cn/docs/community/contributor)

**Comment by f497196689** [comment]
认领

**Comment by agentart** [comment]
@f497196689 欢迎，PR 在跑 CI，稍后合并
