### ISSUE TITLE
docker启动登录异常

### ISSUE THREAD

**Issue by laoxiaokang** [opengoofy/hippo4j#711]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/docs/user_docs/other/issue)

请在提交问题之前回答这些问题，谢谢。

### 实际行为
docker启动 根据文档提供的启动命令，数据库已提前创建好，登录异常，login接口200 无任何返回信息，
![image](https://user-images.githubusercontent.com/45983816/191526290-88a117d6-f0b9-4134-a566-3dfa9358e48f.png)
![image](https://user-images.githubusercontent.com/45983816/191526375-9dbb3775-79aa-4862-8160-c570e8e11f37.png)
![image](https://user-images.githubusercontent.com/45983816/191526501-ad9f50dd-f78b-4f4a-bb9d-2576d530e468.png)
![image](https://user-images.githubusercontent.com/45983816/191526955-efc0d5b8-8c96-454b-b1ad-c7390c1df578.png)

**Comment by itmachen** [comment]
@laoxiaokang 可以贴一下创建 docker 容器的命令，另外把容器内报错日志打印出来。其次，从这几个方面去排查问题：

1. MySQL 是否为容器化部署，还是本地？
2. 如果本地部署，`-e MYSQL_HOST=xxx.xxx.x.x` 需要填写为本机 ip

**Comment by laoxiaokang** [comment]
mysql 部署在云主机的docker上 ip为公网地址

**Comment by laoxiaokang** [comment]
![image](https://user-images.githubusercontent.com/45983816/191545677-23b2aeb1-9da7-4a8f-ae22-af5c3281b096.png)
![image](https://user-images.githubusercontent.com/45983816/191545965-0b052db2-7035-4c81-b2b9-9fc666de158c.png)

**Comment by itmachen** [comment]
不是说 docker 启动错误日志，而是当你访问登录接口时，容器内日志报的错

**Comment by laoxiaokang** [comment]
你的日志目录在哪 也没见挂载啊

**Comment by pirme** [comment]
docker exec -it hippo4j-server bash

tail -f logs/hippo4j-server-info.log

**Comment by laoxiaokang** [comment]
![image](https://user-images.githubusercontent.com/45983816/191691016-58d92261-4c4e-4c96-b062-b8a226cb77be.png)

**Comment by pirme** [comment]
这不是 hippo4j 的问题，请检查你的数据库
