### ISSUE TITLE
修复 Dubbo 错误的日志打印

### ISSUE THREAD

**Issue by iwangjie** [opengoofy/hippo4j#720]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/23075587/192003274-91585eb9-9db7-4133-a1be-48abed7298af.png">

自 #708 修复以后，该日志打印便不再准确，isLegacyVersion 不再作为 dubbo 2 和 dubbo 3 的判断依据，应该使用当前 dubbo 具体版本号。

**Comment by baymax55** [comment]
如何修复呢，在日志中打印当前版本的Dubbo具体版本号吗，Dubbo是否提供接口获取当前版本号呢

**Comment by iwangjie** [comment]
> 如何修复呢，在日志中打印当前版本的Dubbo具体版本号吗，Dubbo是否提供接口获取当前版本号呢

参考 Version.getVersion
