### ISSUE TITLE
ExecutorFactoryTest 补充测试用例

### ISSUE THREAD

**Issue by mageeric** [opengoofy/hippo4j#728]
参考 `cn.hippo4j.common.toolkit.ArrayUtilTest#assertIsEmpty` 完成该单元测试任务。

> 初次提交注意本地 git 配置，参考 [贡献指南](https://hippo4j.cn/docs/community/contributor)

**Comment by zhuiqiugs** [comment]
认领

**Comment by itmachen** [comment]
@zhuiqiugs 欢迎 👏

**Comment by itmachen** [comment]
@zhuiqiugs 请问有在进行么

**Comment by atomFix** [comment]
请问有人在做么，没有的话我接一下

**Comment by pirme** [comment]
@atomFix 已分配
