### ISSUE TITLE
JwtTokenUtilTest 补充测试用例

### ISSUE THREAD

**Issue by mageeric** [opengoofy/hippo4j#735]
参考 `cn.hippo4j.common.toolkit.ArrayUtilTest#assertIsEmpty` 完成该单元测试任务。

> 初次提交注意本地 git 配置，参考 [贡献指南](https://hippo4j.cn/docs/community/contributor)

**Comment by Shiguiwu** [comment]
这个我来 账户 2406749643@qq.com

**Comment by itmachen** [comment]
@Shiguiwu 欢迎 👏

**Comment by Shiguiwu** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by itmachen** [comment]
@Shiguiwu 请问有在进行么

**Comment by Shiguiwu** [comment]
最近有点忙哦&nbsp;


如果╭ァ你愿意
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月16日(星期天) 晚上7:35
收件人: "opengoofy/hippo4j";
抄送: "Mention";
主题: Re: [opengoofy/hippo4j] JwtTokenUtilTest 补充测试用例 (Issue #735)





 
@Shiguiwu 请问有在进行么
 
&mdash;

**Comment by Shiguiwu** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
