### ISSUE TITLE
支持 SpringBoot 2.0 以下版本动态修改线程池

### ISSUE THREAD

**Issue by itmachen** [opengoofy/hippo4j#736]
依赖配置中心动态刷新线程池的 hippo4j-config 在进行动态刷新前，需要将配置中心的 Map 对象转换为具体的动态线程池配置对象。

SpringBoot 2.0 +版本有个 `org.springframework.boot.context.properties.bind.Binder` 可以很好支持该需求，但是低于该版本却没有很好的支持方式。所以 hippo4j config 模式不支持 SpringBoot 2.0 以下版本。

需求：hippo4j config 模式支持 SpringBoot 2.0 以下版本。

具体方法：

- `BootstrapConfigPropertiesBinderAdapt.bootstrapCorePropertiesBinder`

**Comment by liulinfei121** [comment]
认领

**Comment by itmachen** [comment]
@liulinfei121 欢迎 👏

**Comment by pirme** [comment]
@liulinfei121 hello，请问任务有在进行么

**Comment by liulinfei121** [comment]
这个没写出来，想放弃了

**Comment by liulinfei121** [comment]
sorry

**Comment by pirme** [comment]
@liulinfei121 没关系，这个 issue 就继续开放出来了。

**Comment by pizihao** [comment]
OK
