### ISSUE TITLE
数据库  tp_id 字段字段长度为 56，比较短，无法满足某些场景需要

### ISSUE THREAD

**Issue by linlinjie** [opengoofy/hippo4j#737]
## 需求建议
数据库  tp_id 字段字段长度为 56，字段有点短，无法满足某些场景需要
### 描述你想要的功能
建议对tp_id相关字段长度进行调整优化，增大长度

**Comment by pirme** [comment]
修改数据库中所有 tp_id 相关字段长度，涉及以下几个文件：

- https://github.com/opengoofy/hippo4j/tree/develop/hippo4j-server/conf/sql-upgrade 目录下添加 1.4.2_upgrade.sql
- https://github.com/opengoofy/hippo4j/blob/develop/hippo4j-server/conf/hippo4j_manager.sql 修改创建表语句长度
- https://github.com/opengoofy/hippo4j/tree/develop/hippo4j-server/src/main/resources/sql-script/h2 修改创建表语句长度
- https://github.com/opengoofy/hippo4j/tree/develop/hippo4j-server/src/main/resources/sql-script/mysql 修改创建表语句长度
