### ISSUE TITLE
线程池实例运行数据采集，如果线程池id不存在，且长度超长，会报异常：Data truncation: Data too long for column 'tp_id' at row

### ISSUE THREAD

**Issue by linlinjie** [opengoofy/hippo4j#738]
### 你使用了哪个项目？hippo4j config 还是 hippo4j server?
hippo4j server

### 表现行为
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'tp_id' at row 1

### 原因分析（如果可以）
client端在上报运行数据时候，如果该线程池实例id没有配置在server端也会保存数据，
因为没有对上报数据字段有校验，发生了tp_id长度超出数据库限制的问题

### 建议
server 端收到客户端上报数据时，先去查下实例是否存在，如果不存在，应该直接丢弃数据

### 代码位置
上报运行数据入口位置:
cn.hippo4j.console.controller.MonitorController#dataCollect
运行数据处理逻辑位置:
cn.hippo4j.config.service.biz.impl.HisRunDataServiceImpl#save

**Comment by Gdk666** [comment]
认领

**Comment by itmachen** [comment]
@Gdk666 欢迎
