### ISSUE TITLE
替换底层网络工具类 OkHttp

### ISSUE THREAD

**Issue by itmachen** [opengoofy/hippo4j#766]

**Comment by yanrongzhen** [comment]
@itmachen 请问下替换的背景是?

**Comment by itmachen** [comment]
和移除三方工具类的背景类似，okhttp 不同版本之间可能造成部分 api 不兼容。我的想法是，参考 nacos `package com.alibaba.nacos.common.http` 包下自建一套 HTTP 调用工具。

**Comment by yanrongzhen** [comment]
好的, 了解了 👍🏻

**Comment by yanrongzhen** [comment]
@itmachen PR已提交

**Comment by itmachen** [comment]
@yanrongzhen 收到，因为改动比较核心，所以合并不会太快

**Comment by yanrongzhen** [comment]
@itmachen 收到👌
