### ISSUE TITLE
登录index界面报错：登陆失败，实际为数据库连接失败

### ISSUE THREAD

**Issue by jiang972** [opengoofy/hippo4j#787]
环境：windows10,+jdk8
步骤：
1.下载了1.4.1的hippo-server的zip，
2.在公司测试库创建了指定数据库，初始化数据表信息
3.修改了配置文件中的三个配置项：spring.datasource.url，spring.datasource.username，spring.datasource.password，其他均未作修改
4.登录http://localhost:6691/index.html，按照官网指定的账号密码
结果：
登陆失败，查看error日志：
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Caused by: java.net.ConnectException: Connection refused: connect

**Comment by pizihao** [comment]
老哥，这三个你都改成了啥？正常情况下能远程连到数据库吗？

**Comment by jiang972** [comment]
> 

公司测试库，我自己的云服务器，都试过了，连不上。我本机windows肯定是可以链接到数据库的，这三我就改了账号密码，还有服务器地址，后面参数也没动

**Comment by itmachen** [comment]
问题解决了么？我理解这种问题应该不会是 hippo4j 引起的
