### ISSUE TITLE
客户端注册服务端失败，输出服务端返回信息

### ISSUE THREAD

**Issue by wulangcode** [opengoofy/hippo4j#794]
## 需求建议
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/48200100/195277434-fb2bba71-0bbf-4808-ae14-73e92f2b0c17.png">

请在提交问题之前回答这些问题，谢谢。

**Comment by pirme** [comment]
这是个好的建议，您是否有兴趣贡献 PR？

**Comment by wulangcode** [comment]
好的
