### ISSUE TITLE
ResizableCapacityLinkedBlockingQueue可变队列的capacity字段可见性问题

### ISSUE THREAD

**Issue by RookieMember** [opengoofy/hippo4j#808]
ResizableCapacityLinkedBlockingQueue可变队列的capacity字段没有用volatile修饰，可能有可见性问题，建议加上volatile修饰
##
private int capacity;

public void setCapacity(int capacity) {
        final int oldCapacity = this.capacity;
        this.capacity = capacity;
        final int size = count.get();
        if (capacity > size && size >= oldCapacity) {
            signalNotFull();
        }
 }
##

**Comment by pirme** [comment]
ResizableCapacityLinkedBlockingQueue 引用自 RabbitMQ 可变队列，目前经过测试及使用没有发现问题。

**Comment by RookieMember** [comment]
我做了一些测试也没有发现问题，可能只是理论上存在可能吧。。。。。。
