### ISSUE TITLE
阅读源码疑问，修改管理端线程池未执行断点

### ISSUE THREAD

**Issue by zoujin001** [opengoofy/hippo4j#811]
hippo4j-server，管理页面更新线程池实例参数时，刚启动那会儿会走cn.hippo4j.config.controller.ConfigController#publishConfig方法的断点，但是过一会儿后，再次更新，就不走该方法的断点了，但是会成功更新数据信息

<img width="1365" alt="图片" src="https://user-images.githubusercontent.com/45163196/196879906-ebb32056-a8b6-4b84-b7a1-dc2943ec7e14.png">

<img width="1194" alt="图片" src="https://user-images.githubusercontent.com/45163196/196879833-b184c768-6c22-4724-a913-e0052b0ba9bd.png">

**Comment by shanjianq** [comment]
我复述一下问题，首先变更参数的账号是admin。
在debug调试的时候，变更参数请求发出后，断点停在了图中所示72行的角色判断位置，放行后参数变更成功。
然后等一会儿后再次点击变更参数时，是程序没有被相同的断点停住，而是直接执行完毕，参数变更成功。
是这样吗？

**Comment by zoujin001** [comment]
> 我复述一下问题，首先变更参数的账号是admin。 在debug调试的时候，变更参数请求发出后，断点停在了图中所示72行的角色判断位置，放行后参数变更成功。 然后等一会儿后再次点击变更参数时，是程序没有被相同的断点停住，而是直接执行完毕，参数变更成功。 是这样吗？

是的

**Comment by magestacks** [comment]
Issue 长时间没有反馈，关闭。
