### ISSUE TITLE
对接客户端相关接口 HTTP 切换为 RPC

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#812]
目前三方线程池相关接口，是从服务端以 HTTP 的方式请求客户端的，这种方式存在安全问题：

- 客户端 HTTP 可能会被调用。
- 客户端如果有权限相关，还需要额外配置。

所以，希望这块交互变为 RPC 实现。因为现有 RPC 框架有点重，所以这块需要自定义 RPC 相关实现。

**Comment by pizihao** [comment]
认领
