### ISSUE TITLE
DynamicThreadPoolExecutor 重构扩展逻辑

### ISSUE THREAD

**Issue by Createsequence** [opengoofy/hippo4j#815]
我在读源码的时候，发现 `DynamicThreadPoolExecutor` 通过 `ThreadPoolExecutor` 提供的 `execute`、`beforeExecute` 和 `afterExecute` 方法已经提供好了回调的钩子了，而也已经有关于开始时间和结束时间的处理逻辑了，如果要加上这个这三个时间指标的需求，直接在 `DynamicThreadPoolExecutor` 类里加上刷新时间的逻辑就可以。

不过，个人觉得直接往上加代码或许不是一个优雅的解决方案，我注意到目前 `DynamicThreadPoolExecutor` 中已经写入了多种固定的回调逻辑：

- 由 `AbstractDynamicExecutorSupport` 父类提供的线程池中断时等待执行剩余任务的逻辑；
- 由 `RejectedProxyInvocationHandler` 提供的当触发拒绝策略时，通过 `ThreadPoolNotifyAlarmHandler` 发送告警的逻辑；
- 由 `RejectedProxyInvocationHandler` 提供的记录拒绝任务数的逻辑；
- 由 `TaskDecorator` 提供的在执行任务前对 `Runable` 进行包装的逻辑；
- 由 `ThreadPoolNotifyAlarmHandler` 提供的在任务执行后检测任务执行是否超时，并发生告警的逻辑；

这些操作被直接固定在 `DynamicThreadPoolExecutor`，当需要进行扩展的时候——比如现在——往往需要直接修改 `DynamicThreadPoolExecutor` 类本身。

出于更好的管理回调方法，与对 `DynamicThreadPoolExecutor` 本身避免耦合过多功能的方面考虑，是否通过提供类似 `Spring` 的 `Aware` 接口，或是 `PostProcessor`，来统一的向 `DynamicThreadPoolExecutor` 各个执行阶段设置回调方法呢？

比如，我们可以在 `DynamicThreadPoolExecutor` 中设置这样几个回调节点，它们分别对应三个 `Aware` 接口里面的五个方法：

- `ExecuteAware`：提供三个方法，可以在任务执行前、执行时、执行后触发回调；
- `RejectedAware`：提供一个方法，在拒绝策略执行前回调；
- `ShutdownAware`：提供一个方法，在线程池停止前回调；

基于该想法，`DynamicThreadPoolExecutor` 本身可以简化为一个具备注册和管理 `Aware` 接口的纯净类，而各项扩展功能都可以以 `XXXAwareHandler` 的方式挂载到这个核心类上。

比如：

- 执行前包装任务的逻辑可以分离为 `TaskDecoratorExecuteAwareHandler`；

- 任务拒绝时告警的逻辑可以分离为 `NotifyAlarmRejectedAwareHandler`；

- 关闭线程池前等待执行剩余任务的逻辑可以分离为 `TerminationShutdownAwareHandler`；

- 记录线程执行时间的逻辑可以分离为 `TimeWatchExecuteAwareHandler`；

  而根据执行时间选择是否发生超时告警的逻辑则可以基于前者扩展为 `NotifiableTimeWatchExecuteAwareHandler`；

若有必要，用户也可以根据需要比较方便的自行挂载新的 `Aware` 处理器。

_Originally posted by @Createsequence in https://github.com/opengoofy/hippo4j/issues/689#issuecomment-1286637407_

**Comment by itmachen** [comment]
👍

**Comment by Createsequence** [comment]
小马哥，扩展方式改造这个我大概搞定了，现在还在写测试用例，不过遇到一个问题：

有些属性，比如 `executeTimeOut` 这种，在改造以后配置就被分离到对应的插件上了，而 `DynamicThreadPoolExecutor` 又直接提供了 setter/getter 方法，导致现在为了适配，必须写成这样：

~~~java
public void setExecuteTimeOut(Long timeOut) {
    // 先获取已注册的插件
    TaskTimeoutNotifyAlarmPlugin plugin = pluginManager.get("TaskTimeoutNotifyAlarmPlugin");
    // 修改插件参数
    plugin.setTaskTimeout("timeOut");
}
~~~

这样也不影响使用，不过感觉还是有点怪怪的。

我又看了看第三方线程池适配和刷新配置那边，发现有些非 `DynamicThreadPoolExecutor` 的线程池实例是不支持这些配置，所以我有了一个大胆的想法：

线程池本身应当只支持 `ThreadPoolExecutor` 本身提供的那些修改的 API，关于这部分的配置是所有线程池都支持的，但是有些扩展功能的配置只有 `DynamicThreadPoolExecutor` 才支持，比如执行超时告警这种。

换个角度理解，第三方的线程池也好，`hipp4j` 的 `DynamicThreadPoolExecutor` 也好，它们都是完全一样的线程池，都是 `ThreadPoolExecutor`，只不过有的有安插件，有的没有安插件，按了什么插件就支持什么功能，同理，这个功能来自于插件，所以改配置也只需要改插件的配置就行。

按这个思路，有些扩展功能的配置就可以分离到插件上，比如，我们可以把配置文件加一个目录：

~~~yml
dynamic:
 # 通用配置
 thread-pool-id: foo
 core-pool-size: 50
 max-pool-size: 100

 # 插件配置
 plugins:
  # 配置线程池关闭插件
  pool-shutdown-plug:
   enable: true
   await-termination-millis: 1000
   is-wait-for-tasks-to-complete-on-shutdown: true
  # 配置任务超时告警插件
  task-timeout-notify-plug:
   enable: true
   execute-time-out: 1000
  # 用户自定义插件
  cutstome-plug:
   enable: true
   custome-option: foo
~~~

当需要线程池配置的时候，就没必要一个一个判断类型并 set 参数，直接把线程池实例里的插件管理器（如果有的话）取出来，然后按 `plugin`  中的 `id` 把那个插件拉出来（如果有的话），再用 `Binder` 把配置中心发下来的配置绑上去就行了。

同理，展示的时候统一的把扩展配置移到 `plugins` 属性里，里面的信息也不用 get 再 set，甚至可以直接把插件实例扔进去转成 JSON 返回出去；

这个做法的好处是：

- 对于非原生 `ThreadPoolExecutor` 支持的功能，可以统一通过插件管理器进行隔离，这样就不必与 `DynamicThreadPoolExecutor` 进行强耦合，万一以后 `DynamicThreadPoolExecutor` 又加了个子类支持新功能，也不用改旧代码，反正扩展功能都是面向插件的；
- 提供更细粒度的扩展功能管理，比如告警平台有点问题，或者队列压力很大，这个时候就可以临时先把一些不重要的功能停了，比如任务拒绝告警，或者任务超时告警；
- 对于第三方线程池，只要能挂载上插件中心，把回调通过字节码或者代理的方式埋进去，那么他们同样也可以支持这些扩展功能；
- 如果用户想写自己的插件，仅需要写代码然后在启动的时候注册到插件中心即可，后续一些线上配置调整，或者需要展示配置信息这些全都不需要特殊处理，直接无缝接入；

这个是大概的一个大胆的想法，如果要做的话无疑是一个超级大工程，但是真到了看起来好像也有不少的好处？

**Comment by weihubeats** [comment]
这里可以理解为你所谓的插件化是在AbstractBuildThreadPoolTemplate类中添加一个插件接口，然后去填充属性吗？

**Comment by weihubeats** [comment]
这里可以理解为你所谓的插件化是在AbstractBuildThreadPoolTemplate类中添加一个插件接口，然后去填充属性吗？

**Comment by itmachen** [comment]
这是一个很好的想法。

结合目前 hippo4j 的现状，我有两点问题：

1. 如果升级到上述提到的架构，客户端的改造成本大概有什么？
2. config 模式下有个线程池默认配置，不清楚是否适配？内容请参考 [默认配置](https://hippo4j.cn/docs/user_docs/getting_started/config/hippo4j-config-default)

**Comment by weihubeats** [comment]
非常好的建议，但是我们还是需要讨论下:
1. 能否提供一个插件接口的定义看看
2. 停掉告警这个优点现在删除配置也可以停止掉吧
3. 插件的插入是在构造线程池阶段去插入吗？比如插件定义在DynamicThreadPoolExecutor中

**Comment by Createsequence** [comment]
emmmm两位大佬的评论我一起回复一下吧：

### 1.如果升级到上述提到的架构，客户端的改造成本大概有什么？

这一点可能是比较主要的问题，大概有以下几部分：

- 扩展功能相关的部分配置文件写法需要调整，比如从原来的放在根目录调整为放在 `plugins.xxxPlugins` 下；
- 前端页面接口可能需要调整，同上，可能需要增加一级目录，或者在后端进行手动平铺；
- 直接使用到 `DynamicThreadPoolExecutor` 类扩展参数——即要分离到插件的属性和功能——需要调整，这一点可能是最麻烦的；

### 2. config 模式下有个线程池默认配置，不清楚是否适配？

计算机科学领域的任何问题都可以通过增加一个间接的中间层来解决，问题2描述的场景有一个非常有参考价值的方案，那就是 SpringBoot 的 starter，我们可以提供一个配置包——或者叫注册器——来封装一组配置，从而实现开箱即用的效果。

比如针对 `DynamicThreadPoolExecutor` 的默认具备的五大功能，我们可以封装一个默认的注册器，用户只需要配置这个注册器就能完成所有默认组件的配置，例如：

~~~java
public class DefaultThreadPoolPluginRegistrar
    implements ThreadPoolPluginRegistrar, ApplicationContextAware, BeanNameAware {
    private final long executeTimeOut;
    private final long awaitTerminationMillis;
    private final boolean waitForTasksToCompleteOnShutdown;
    @Override
    public void doRegister(ThreadPoolPluginRegistry registry, ExtensibleThreadPoolExecutor executor) {
        // callback when task execute
        registry.register(new TaskDecoratorPlugin());
        registry.register(new TaskTimeoutNotifyAlarmPlugin(executeTimeOut, executor));
        // callback when task rejected
        registry.register(new TaskRejectCountRecordPlugin());
        registry.register(new TaskRejectNotifyAlarmPlugin());
        // callback when pool shutdown
        registry.register(new ThreadPoolExecutorShutdownPlugin(awaitTerminationMillis, waitForTasksToCompleteOnShutdown));
    }
}
~~~

对应到配置，我们可以加一个属性，叫 registrar，比如：

~~~yml
spring:
  dynamic:
    thread-pool:
     default-plugin-registrars:
      - DefaultThreadPoolPluginRegistrar:
         enable: true
         execute-time-out: 1000
         await-termination-millis: 1000
      - FooDefaultThreadPoolPluginRegistrar:
         enable: true
~~~

如此即可默认为所有线程池完成插件注册，与默认配置同理，若有不同的配置则以具体线程池的配置为准。

### 4、能否提供一个插件接口的定义看看

待会我提一个临时性的 PR，你们可以瞅瞅我大概的想法；

### 5、停掉告警这个优点现在删除配置也可以停止掉吧

是的，实际上插件机制本身基本不带来新功能，有些功能有没有插件机制都是能够实现的。插件机制只是重构并扩展搭建一个更灵活的框架，它会为后续功能的扩展和改造带来更多好处。

### 6、插件的插入是在构造线程池阶段去插入吗？比如插件定义在DynamicThreadPoolExecutor中

在我的想法里，插件的所有行为都由线程池实例绑定的插件管理器管理，线程池本身只负责在调用回调方法的时候向管理器获取插件，只要在线程池构建的时候有管理器就行了，换句话说，插件本身就是支持热插拔的，什么向插件管理器注册插件并不重要。

**Comment by pirme** [comment]
这块涉及到前端的功能变更么？目前前端项目参考 http://console.hippo4j.cn/index.html#/dashboard

**Comment by Createsequence** [comment]
> 这块涉及到前端的功能变更么？目前前端项目参考 http://console.hippo4j.cn/index.html#/dashboard

它只是个重构，不会增加新的功能，目前看来，对控制台的影响可能是需要调整一下部分接口的入参和返回值的对象结构，比如：
原本的对象可能是这样的：

~~~json
{
    "id": "foo",
    "executeTimeOut": 5000
}
~~~

后面可能会改成这样：

~~~java
{
    "id": "foo",
    "plugins": [
        {
            "plugId": "TaskExecuteTimeOutPlugin",
            "executeTimeOut": 5000
        }
    ]
}
~~~

不过在没有考虑新增太多功能的情况下，可以先不改，由后端手动适配成旧的对象。

当然，虽然这么说，也许也会有意想不到的问题，所以这个重构的建议还是需要慎重点考虑。

**Comment by pirme** [comment]
明白了，这个重构是很有意义的，只是希望咱们能够分步骤走，以客户端最小改动的前提进行

**Comment by weihubeats** [comment]
> > 这块涉及到前端的功能变更么？目前前端项目参考 http://console.hippo4j.cn/index.html#/dashboard
> 
> 它只是个重构，不会增加新的功能，目前看来，对控制台的影响可能是需要调整一下部分接口的入参和返回值的对象结构，比如： 原本的对象可能是这样的：
> 
> ```json
> {
>     "id": "foo",
>     "executeTimeOut": 5000
> }
> ```
> 
> 后面可能会改成这样：
> 
> ```java
> {
>     "id": "foo",
>     "plugins": [
>         {
>             "plugId": "TaskExecuteTimeOutPlugin",
>             "executeTimeOut": 5000
>         }
>     ]
> }
> ```
> 
> 不过在没有考虑新增太多功能的情况下，可以先不改，由后端手动适配成旧的对象。
> 
> 当然，虽然这么说，也许也会有意想不到的问题，所以这个重构的建议还是需要慎重点考虑。

这个改动和思想是非常好的，但是由于改动太大，直接merge的风险太大，所以还是需要评估，其次我们限有测试用例暂时不支持这么大的重构，我们可以换个方式比如，先定义好插件的整体框架，然后慢慢提替，类似敏捷开发，这样的风险会小一点。我们这边还是需要继续评估下，感谢您的PR。

**Comment by Createsequence** [comment]
> > > 这块涉及到前端的功能变更么？目前前端项目参考 http://console.hippo4j.cn/index.html#/dashboard
> > 
> > 
> > 它只是个重构，不会增加新的功能，目前看来，对控制台的影响可能是需要调整一下部分接口的入参和返回值的对象结构，比如： 原本的对象可能是这样的：
> > ```json
> > {
> >     "id": "foo",
> >     "executeTimeOut": 5000
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 后面可能会改成这样：
> > ```java
> > {
> >     "id": "foo",
> >     "plugins": [
> >         {
> >             "plugId": "TaskExecuteTimeOutPlugin",
> >             "executeTimeOut": 5000
> >         }
> >     ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不过在没有考虑新增太多功能的情况下，可以先不改，由后端手动适配成旧的对象。
> > 当然，虽然这么说，也许也会有意想不到的问题，所以这个重构的建议还是需要慎重点考虑。
> 
> 这个改动和思想是非常好的，但是由于改动太大，直接merge的风险太大，所以还是需要评估，其次我们限有测试用例暂时不支持这么大的重构，我们可以换个方式比如，先定义好插件的整体框架，然后慢慢提替，类似敏捷开发，这样的风险会小一点。我们这边还是需要继续评估下，感谢您的PR。

目前的pr也是这么做的，在这个阶段的改动是基本没有影响原有api的。不过重构确实也应当谨慎的进行，我只是提出了一个有意思的想法，并且验证了一下可行性。实际上，这个重构是否是过度设计，是否会对整体带来的一些其他的问题和风险，我有限的经验也没有办法提前预料到，因此我还是尊重你们的决定。

基于该pr后续还有一个issuse＃689的pr，如果现在这个方案风险太大的话，我会换个方案实现，不过可能要推迟点。

**Comment by pirme** [comment]
经过沟通，会以目前的 PR 进行功能验收，请知悉～

**Comment by Createsequence** [comment]
> 经过沟通，会以目前的 PR 进行功能验收，请知悉～

ok
