### ISSUE TITLE
调整线程池构建通知参数优先级

### ISSUE THREAD

**Issue by magegoofy** [opengoofy/hippo4j#825]

**Comment by baymax55** [comment]
调整后出现 `notifyConfigs `map无法进行赋值,导致后续进行通知时无法从该map中获取到对应的key,从而无法进行推送

>` cn.hippo4j.springboot.starter.notify.ServerNotifyConfigBuilder#buildNotify` 方法内的 threadPoolIds 会为空,而改用CommandLineRunner 接口则不会为空

**Comment by baymax55** [comment]
@magegoofy

**Comment by magegoofy** [comment]
什么场景下出现的这种问题

**Comment by baymax55** [comment]
![1](https://user-images.githubusercontent.com/35788491/199458087-1b291ebc-95db-4292-b01d-bd6c0c37f28d.jpg)
![2](https://user-images.githubusercontent.com/35788491/199458096-45d6d89e-485e-484c-8617-7562fa6d6f1b.jpg)

**Comment by baymax55** [comment]
> 前提 最新版devlop分支代码

1.启动hippo4j-server服务
2.启动hippo4j-spring-boot-starter-example 服务
  2.1 cn.hippo4j.message.service.Hippo4jBaseSendMessageService 实现 org.springframework.beans.factory.InitializingBean 接口会导致该现象发生

**Comment by magegoofy** [comment]
提个 PR 修复下吧先，别耽误正常开发。
