### ISSUE TITLE
hippo4j-example CheckStyle ERROR 修复

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#833]
参考 https://github.com/opengoofy/hippo4j/issues/826

**Comment by hncboy** [comment]
这个处理了吗，我看大都是魔法值

**Comment by magestacks** [comment]
还没有处理，示例项目中大多数确实是魔法值问题

**Comment by sususama** [comment]
@magestacks Hi, 这个问题处理了吗？我看到在 #826 已经被 #940 解决。如果解决的话还有其他的Good first issue吗？

**Comment by magestacks** [comment]
@sususama 在该 issue 下留言 https://github.com/opengoofy/hippo4j/issues/1148
