### ISSUE TITLE
docker-startup.sh的mysql配置多个“-”

### ISSUE THREAD

**Issue by CloudyGM** [opengoofy/hippo4j#839]
### 你使用了哪个项目？
hippo4j server
### 你使用了哪个版本？
1.4.2
### 原因分析（如果可以）
hippo4j-server/docker-startup.sh文件的第23行
参数多一个“-”
![image](https://user-images.githubusercontent.com/33982485/197538740-04fecd37-31e6-4023-8036-ce086590a382.png)

**Comment by itmachen** [comment]
可以提交个 PR 修复下么

**Comment by Malcolmli** [comment]
已提交
