### ISSUE TITLE
配置未发生变更时，长轮询返回 304

### ISSUE THREAD

**Issue by wulangcode** [opengoofy/hippo4j#845]
## 需求建议
长轮训服务端未变更时，返回code 304 的状态码

HTTP304状态码代表的意思是请求资源与本地缓存相同，未修改，即HTTP 304 Not Modified 响应状态。

请在提交问题之前回答这些问题，谢谢。

### 您的功能请求是否与问题有关？
无
### 描述你想要的功能
区别 code 200 与 304 的返回状态码

**Comment by pirme** [comment]
我理解，这个 issue 的建议是，长轮训服务端未变更时，返回合适的状态码是吧
