### ISSUE TITLE
服务端在客户端后面启动，依旧支持长轮训

### ISSUE THREAD

**Issue by wulangcode** [opengoofy/hippo4j#846]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/docs/user_docs/other/issue)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?
hippo4j config

### 你使用了哪个版本？
latest

### 预期行为
客户端在服务端前面启动，之后服务端启动，客户端恢复连接后，依旧支持长连接

### 实际行为
客户端启动时，若服务报错，则不注册进入本地map，导致不进入长轮训。

### 原因分析（如果可以）
不启动服务端，先启动 `ServerExampleApplication`,到 `DynamicThreadPoolPostProcessor#fillPoolAndRegister` 方法时
<img width="1850" alt="image" src="https://user-images.githubusercontent.com/48200100/197781425-8253b7fa-ec64-44f8-9023-773945ca54d7.png">
当进入`DynamicThreadPoolPostProcessor#subscribeConfig`方法时
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/48200100/197781726-7567e1bb-91b8-46e6-bda1-44ba227d1de4.png">
此时`ClientWorker` 构造器中
<img width="1567" alt="image" src="https://user-images.githubusercontent.com/48200100/197782051-06c5c2a7-83bc-486f-b14b-acf0797749b3.png">

问题解决：
1、
`cn.hippo4j.core.executor.DynamicThreadPoolWrapper#subscribeFlag`字段不应该根据服务端的返回状态，只要是 `DynamicThreadPoolExecutor`类型都应该进入 `ClientWorker#cacheMap` 中；

2、
是否启动长轮训不应该在构造器中判断，因为应该让用户自己往`ClientWorker#cacheMap`中注入需要监听的线程，这种线程池可能也不是`DynamicThreadPoolExecutor`类型，建议如下修改
1. 删除进入长轮训的判断
2. 长轮训中如果`ClientWorker#cacheMap` 中是空，则睡眠后，再进入下次长轮训，也好规避[#803 ]的问题
### 问题重现步骤
先启动客户端，再启动服务端

**Comment by pirme** [comment]
这个可以互相讨论下，如果客户端启动时，服务端未存活，是否应该保持长链接。

我以为，正常流程启动，服务端不存在未存活情况，所以这里的逻辑可能是合理的。

**Comment by HakChealKim** [comment]
微服务架构下，很多服务即是客户端也是服务端。是不是有可能发生上述情况？

**Comment by wulangcode** [comment]
1. 必须强制要求服务端在客户端前面启动，这是不合理的。存在这种情况，比如客户端启动时，服务端被操作系统 kill 掉，这种情况是对用户来说是无意识的，若想保持现在这种情况，潜台词是**客户端启动时必须要服务端能正常响应**，但实际情况是并不能完全保证。
2. 长轮训应该采用步进的睡眠时间，`5s -> 10s -> 30s -> 60s -> 60s` 等以此类推

**Comment by itmachen** [comment]
统一回复下：

1. 可以在适配客户端启动时服务端被 Kill 的情况。
2. 我理解第 2 点应该指的是连接不到服务端的健康扫描时间，目前就是按照步长的方式完成的。

**Comment by itmachen** [comment]
> 微服务架构下，很多服务即是客户端也是服务端。是不是有可能发生上述情况？

hippo4j 客户端和服务端是完全分离的。
