### ISSUE TITLE
docker部署 mysql启动报错H2驱动

### ISSUE THREAD

**Issue by Malcolmli** [opengoofy/hippo4j#851]
### 你使用了哪个项目？
hippo4j server
### 你使用了哪个版本？
1.4.2
### 问题重现步骤
docker参数设置mysql 项目启动后登录接口报错
### 用于重现此问题的示例代码（例如 GitHub 链接）
![image](https://user-images.githubusercontent.com/33982485/198172227-7790ed49-5f42-4081-8d64-965736579edd.png)
![image](https://user-images.githubusercontent.com/33982485/198172285-448b4b1e-8543-4eb5-81b3-4d65e6b5740e.png)

**Comment by pirme** [comment]
确定为 MySQL 未生效问题。通过以下 SQL 默认还是 H2。

```shell
docker run -d -p 6691:6691 --name hippo4j-server -e DATASOURCE_HOST=xxx -e DATASOURCE_PORT=3306 -e DATASOURCE_DB=hippo4j_manager -e DATASOURCE_USERNAME=root -e DATASOURCE_PASSWORD=root hippo4j/hippo4j-server
```

查看 Docker 启动日志：

```shell
INFO Execute hippo4j schema sql: sql-script/h2/hippo4j_manager.sql
```

**Comment by Malcolmli** [comment]
问题已解决
