### ISSUE TITLE
TaskTimeoutNotifyAlarmPlugin#recordTaskTime 任务执行超时判断不应该包含加锁逻辑

### ISSUE THREAD

**Issue by magegoofy** [opengoofy/hippo4j#879]
## 需求建议

请在提交问题之前回答这些问题，谢谢。

### 您的功能请求是否与问题有关？

无

### 描述你想要的功能

```java
@Override
protected void recordTaskTime(long executeTime) {
    super.recordTaskTime(executeTime);
    if (executeTime <= executeTimeOut) {
        return;
    }
    Optional.ofNullable(ApplicationContextHolder.getInstance())
            .map(context -> context.getBean(ThreadPoolNotifyAlarmHandler.class))
            .ifPresent(handler -> handler.asyncSendExecuteTimeOutAlarm(
                    threadPoolId, executeTime, executeTimeOut, threadPoolExecutor));
}
```

`TaskTimeoutNotifyAlarmPlugin#recordTaskTime` 在执行判断任务执行是否超时时，会调用父类 `TaskTimeRecordPlugin#recordTaskTime` 进行加锁处理。

`TaskTimeoutNotifyAlarmPlugin#recordTaskTime` 方法中，我理解 `super.recordTaskTime(executeTime);` 这行代码是不需要的。

**Comment by Createsequence** [comment]
你是对的，这部分确实点问题。

首先这么写的原因是这两个插件都需要依赖于`获得当前任务执行时间`这个特定的功能：

- `TaskTimeRecordPlugin`：需要根据这个时间用于统计总的线程池任务执行时间；
- `TaskTimeoutNotifyAlarmPlugin`：需要根据这个时间用于判断该任务执行是否超时；

最开始这两个功能是写一起的，后面觉得可能会有只需要记录时间而不需要告警，而没有想到只需要告警而不需要记录时间，所以拆成了现在这样的父子类，`TaskTimeoutNotifyAlarmPlugin` 直接在父类记录时间后再执行告警判断。

现在看来这个拆分是不合理的，获得 `获得当前任务执行时间` 这个逻辑应该是独立的，然后 `TaskTimeRecordPlugin` 和 `TaskTimeoutNotifyAlarmPlugin` 分别基于此去扩展自己的逻辑。

后面我再发一个 PR 重构一下。
