### ISSUE TITLE
线程池检查活跃度报警取值错误

### ISSUE THREAD

**Issue by pirme** [opengoofy/hippo4j#900]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/docs/user_docs/other/issue)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?

all

### 你使用了哪个版本？

latest

### 预期行为

-

### 实际行为

-

### 原因分析（如果可以）

活跃度报警检查使用的容量报警参数。

### 问题重现步骤

-

### 用于重现此问题的示例代码（例如 GitHub 链接）

-

**Comment by maxisvest** [comment]
已修复
