### ISSUE TITLE
线程池实例包含已关闭客户端节点

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#979]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/docs/user_docs/other/issue)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?

hippo4j server

### 你使用了哪个版本？

latest

### 预期行为

线程池实例仅展示正常运行客户端实例。

### 实际行为

线程池实例展示正常以及非正常运行客户端实例。

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/77398366/201522399-e9eb6ed3-0b34-4496-9804-acb391f3de9d.png">

### 原因分析（如果可以）

ip port 一致。

**Comment by Gdk666** [comment]
认领

**Comment by magestacks** [comment]
问题原因见：#1121 已修复
