### ISSUE TITLE
使用prometheus+grafana监控,没有dynamic_thread_pool_ 前缀的指标

### ISSUE THREAD

**Issue by towardsvast** [opengoofy/hippo4j#994]
1. 首先按照文档所示,为项目配置动态监控

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/112958315/202459304-ec27d811-4b2b-4348-84a8-492e0880765c.png">

2. 访问http://localhost:29999/actuator/prometheus 没有发现 dynamic_thread_pool_ 前缀的指标.搜索结果如下:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/112958315/202460335-881424c5-7958-4760-be1b-c8c61706b054.png">

**Comment by magestacks** [comment]
以下包是否有引用

```xml
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>micrometer-registry-prometheus</artifactId>
</dependency>

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
```

**Comment by magestacks** [comment]
看配置，项目启动 10 秒后才会采集

**Comment by towardsvast** [comment]
> 

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/112958315/202486242-9ec49a58-bf47-4f07-8f73-ac21012a05e6.png">
引用了依赖的,并且避免依赖冲突,指定了依赖版本.项目启动时间也在10s以上.辛苦大佬这么晚的回复

**Comment by magestacks** [comment]
项目是否有打印该行日志，如果没有确认下是否配置动态线程池以及 hippo4j 是否被启用

<img width="1611" alt="image" src="https://user-images.githubusercontent.com/77398366/202487390-2219ee12-64e7-41f8-aee1-b6a6b7e4d667.png">

**Comment by towardsvast** [comment]
> 项目是否有打印该行日志，如果没有确认下是否配置动态线程池以及 hippo4j 是否被启用
> 
> <img alt="image" width="1611" src="https://user-images.githubusercontent.com/77398366/202487390-2219ee12-64e7-41f8-aee1-b6a6b7e4d667.png">

- 有打印该行日志
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/112958315/202488601-75899af6-2509-4cc4-bb1a-a9e370be20ea.png">

- 动态线程池也配置了
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/112958315/202488793-d2b1feae-0875-4113-884b-59dfda02efc6.png">

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/112958315/202489105-f67f32f1-e0f5-497d-9b26-a52e69796b45.png">

**Comment by magestacks** [comment]
引用的 hippo4j 客户端版本号是多少

**Comment by magestacks** [comment]
可以和示例项目比对下，看有哪些区别

<img width="511" alt="image" src="https://user-images.githubusercontent.com/77398366/202490515-23b18fd5-d4c5-46df-a6aa-abeb34f6246e.png">


另外，可以 debug 下监控源码，`cn.hippo4j.springboot.starter.monitor.ReportingEventExecutor`

**Comment by towardsvast** [comment]
> monitor

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/112958315/202490818-bb8317e5-6151-4e91-a223-41753311b80a.png">
1.4.3的版本,我先对照看一下.麻烦了,大佬早点休息,还要继续为爱发电呢

**Comment by yiyingcanfeng** [comment]
> > monitor
> 
> <img alt="image" width="1022" src="https://user-images.githubusercontent.com/112958315/202490818-bb8317e5-6151-4e91-a223-41753311b80a.png">
> 
> 1.4.3的版本,我先对照看一下.麻烦了,大佬早点休息,还要继续为爱发电呢

我对比了下example项目，发现还需要引入hippo4j-spring-boot-starter-monitor-micrometer    
```xml
<dependency>
    <groupId>cn.hippo4j</groupId>
    <artifactId>hippo4j-spring-boot-starter-monitor-micrometer</artifactId>
    <version>1.4.3-upgrade</version>
</dependency>
```
才行，不过到我回复的时间为止，阿里maven还没有更新hippo4j-spring-boot-starter-monitor-micrometer 1.4.3-upgrade版本，可以引入hippo4j-monitor-micrometer  
```xml
<dependency>
    <groupId>cn.hippo4j</groupId>
    <artifactId>hippo4j-monitor-micrometer</artifactId>
    <version>1.4.3-upgrade</version>
</dependency>
```
加一个配置类: [MicrometerMonitorAutoConfiguration](https://github.com/opengoofy/hippo4j/blob/develop/hippo4j-spring-boot/hippo4j-spring-boot-starter-monitor/hippo4j-spring-boot-starter-monitor-micrometer/src/main/java/cn/hippo4j/springboot/starter/monitor/micrometer/MicrometerMonitorAutoConfiguration.java)
```java
@Configuration
@ConditionalOnExpression("'${spring.dynamic.thread-pool.monitor.collect-types:}'.contains('micrometer')")
public class MicrometerMonitorAutoConfiguration {

    @Bean
    @ConditionalOnExpression("'${spring.dynamic.thread-pool.monitor.thread-pool-types:}'.contains('dynamic')")
    public DynamicThreadPoolMicrometerMonitorHandler dynamicThreadPoolMicrometerMonitorHandler() {
        return new DynamicThreadPoolMicrometerMonitorHandler();
    }

    @Bean
    @ConditionalOnExpression("'${spring.dynamic.thread-pool.monitor.thread-pool-types:}'.contains('web')")
    public WebThreadPoolMicrometerMonitorHandler webThreadPoolMicrometerMonitorHandler() {
        return new WebThreadPoolMicrometerMonitorHandler();
    }

    @Bean
    @ConditionalOnExpression("'${spring.dynamic.thread-pool.monitor.thread-pool-types:}'.contains('adapter')")
    public AdapterThreadPoolMicrometerMonitorHandler adapterThreadPoolMicrometerMonitorHandler() {
        return new AdapterThreadPoolMicrometerMonitorHandler();
    }
}
```
作为替代
@mageeric 希望文档里线程池监控一节能补充一下

**Comment by towardsvast** [comment]
> 

刚刚验证了一下，确实可以了，感谢大佬解答。 @mageeric 希望线程池监控的文档可以补充一下

**Comment by towardsvast** [comment]
> > > monitor
> > 
> > 
> > <img alt="image" width="1022" src="https://user-images.githubusercontent.com/112958315/202490818-bb8317e5-6151-4e91-a223-41753311b80a.png">
> > 1.4.3的版本,我先对照看一下.麻烦了,大佬早点休息,还要继续为爱发电呢
> 
> 我对比了下example项目，发现还需要引入hippo4j-spring-boot-starter-monitor-micrometer
> 
> ```
> <dependency>
>     <groupId>cn.hippo4j</groupId>
>     <artifactId>hippo4j-spring-boot-starter-monitor-micrometer</artifactId>
>     <version>1.4.3-upgrade</version>
> </dependency>
> ```
> 
> 才行，不过到我回复的时间为止，阿里maven还没有更新hippo4j-spring-boot-starter-monitor-micrometer 1.4.3-upgrade版本，可以引入hippo4j-monitor-micrometer
> 
> ```
> <dependency>
>     <groupId>cn.hippo4j</groupId>
>     <artifactId>hippo4j-monitor-micrometer</artifactId>
>     <version>1.4.3-upgrade</version>
> </dependency>
> ```
> 
> 加一个配置类: [MicrometerMonitorAutoConfiguration](https://github.com/opengoofy/hippo4j/blob/develop/hippo4j-spring-boot/hippo4j-spring-boot-starter-monitor/hippo4j-spring-boot-starter-monitor-micrometer/src/main/java/cn/hippo4j/springboot/starter/monitor/micrometer/MicrometerMonitorAutoConfiguration.java)
> 
> ```java
> @Configuration
> @ConditionalOnExpression("'${spring.dynamic.thread-pool.monitor.collect-types:}'.contains('micrometer')")
> public class MicrometerMonitorAutoConfiguration {
> 
>     @Bean
>     @ConditionalOnExpression("'${spring.dynamic.thread-pool.monitor.thread-pool-types:}'.contains('dynamic')")
>     public DynamicThreadPoolMicrometerMonitorHandler dynamicThreadPoolMicrometerMonitorHandler() {
>         return new DynamicThreadPoolMicrometerMonitorHandler();
>     }
> 
>     @Bean
>     @ConditionalOnExpression("'${spring.dynamic.thread-pool.monitor.thread-pool-types:}'.contains('web')")
>     public WebThreadPoolMicrometerMonitorHandler webThreadPoolMicrometerMonitorHandler() {
>         return new WebThreadPoolMicrometerMonitorHandler();
>     }
> 
>     @Bean
>     @ConditionalOnExpression("'${spring.dynamic.thread-pool.monitor.thread-pool-types:}'.contains('adapter')")
>     public AdapterThreadPoolMicrometerMonitorHandler adapterThreadPoolMicrometerMonitorHandler() {
>         return new AdapterThreadPoolMicrometerMonitorHandler();
>     }
> }
> ```
> 
> 作为替代 @mageeric 希望文档里线程池监控一节能补充一下

刚刚验证了一下，确实可以了，感谢大佬解答。 @mageeric 希望线程池监控的文档可以补充一下

**Comment by magestacks** [comment]
@yiyingcanfeng @towardsvast 这一块疏忽了，我的问题。

另外我解释下监控设计的理念：

1. Config 模式默认带 micrometer，是因为没有内置的监控手段。
2. Server 模式默认不带 micrometer，是因为内置了与服务端的数据监控交互。

我会把 Server 开启 micrometer 监控的相关文档再完善下，感谢指正。

**Comment by magestacks** [comment]
官网已更新

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/77398366/203320018-655b64a3-ea69-4a48-8a12-6de43daf53fa.png">
